- src/protocols/rdp/rdp.c
The "drdynvc" plugin seems to segfault in older versions of FreeRDP, but the plugin is only needed for display update channel support (which is not provided in the affected older versions). The plugin should be loaded only when actually needed, and only when that need is supported by the underlying FreeRDP.
> GUAC-1164: Do not load "drdynvc" plugin unless actually needed.

- src/protocols/rdp/client.c
- src/protocols/rdp/guac_rdpdr/rdpdr_fs_service.c
- src/protocols/rdp/rdp.c
From [GUAC-1517](https://glyptodon.org/jira/browse/GUAC-1517):
> After the RDP session is disconnected and reconnected, the filesystem object for the RDPDR drive, SFTP, etc. is recreated, but the original object is never freed and undefined. The client thus has an ever-increasing stack of filesystems in the Guacamole menu, only the most recent of which will actually be functional.
This change allocates the SFTP and RDP-specific filesystems only once per Guacamole connection, even if RDP reconnects. As neither of these filesystem implementations actually use the RDP client/connection (they are only used *by* the RDP client), this is OK.
> GUAC-1517: Only allocate filesystem objects once per Guacamole connection.

- src/libguac/guacamole/user-fntypes.h
- src/libguac/guacamole/user.h
- src/libguac/user-handlers.c
- src/libguac/user-handlers.h
This change adds support for the "audio" instruction when received from a connected user. Prior to this, audio streams were only provided in the outbound direction, with inbound handling of the "audio" instruction restricted to the JavaScript `Guacamole.Client` class.
> GUAC-1511: Add low-level support for audio input to libguac.

- src/protocols/rdp/client.c
- src/protocols/rdp/rdp.c
There is no need to repeatedly reallocate the audio stream. Just as with RDPDR in #4, the RDPSND implementation is what depends on the RDP connection. The underlying audio stream object does not.
> GUAC-1517: Only allocate one audio stream for RDP connection.

- src/protocols/rdp/rdp.c
- src/protocols/ssh/ssh.c
- src/protocols/vnc/vnc.c
From [GUACAMOLE-34](https://issues.apache.org/jira/browse/GUACAMOLE-34):
> This is caused by the lack of `guac_client_abort()` or `guac_client_stop()` call in some cases where the client thread otherwise terminates. The connection will full close under ONLY the following circumstances:
> 
> 1. All users disconnect (close their browser tabs, manually select "Disconnect" within the guac menu, etc.)
> 2. `guac_client_stop()` is called
> 3. `guac_client_abort()` is called
> 
> If the internal client disconnects and terminates its own thread, it should also invoke `guac_client_stop()` or `guac_client_abort()` to ensure connected users are forced off. Otherwise, users will be confused why their connection remains active with an unresponsive remote desktop session.
> GUACAMOLE-34: Ensure client is cleaned up whenever the client thread terminates.

- src/common/guac_cursor.c
- src/common/guac_cursor.h
- src/protocols/rdp/user.c
- src/protocols/rdp/user.h
- src/protocols/ssh/user.c
- src/protocols/ssh/user.h
- src/protocols/telnet/user.c
- src/protocols/telnet/user.h
- src/protocols/vnc/client.c
- src/protocols/vnc/user.c
- src/protocols/vnc/user.h
From [GUACAMOLE-33](https://issues.apache.org/jira/browse/GUACAMOLE-33):
> This is caused by the lack of a mechanism to signal `guac_common_cursor` of a leaving user. Such a mechanism used to exist, but was removed when thought unnecessary.
> 
> It turns out this is actually necessary, as there is otherwise no guarantee that a newly-allocated user will have a different memory address from the user that just left, and thus certain cursor updates (such as the setting of opacity) may be omitted under the assumption that the user must be the same. *This assumption can fail frequently*, as the memory manager will often service a memory allocation request using a recently-freed memory block.
> GUACAMOLE-33: Fix duplication of mouse cursors

- src/protocols/rdp/audio_input.c
- src/protocols/rdp/ptr_string.c
- src/protocols/rdp/ptr_string.h
The current code leaks the storage for the stringified pointer allocated by `guac_rdp_ptr_to_string()`, but it's really not necessary allocate the string at all. Better that `guac_rdp_ptr_to_string()` be provided a sufficiently-large buffer.
> GUACAMOLE-25: Avoid unnecessary allocation of temporary string for guac_rdp_ptr_to_string().

- src/protocols/rdp/guac_rdpdr/rdpdr_printer.c
- src/protocols/rdp/guac_rdpdr/rdpdr_printer.h
This change replaces the old printing thread with a handler for the "ack" responses sent by the client. Rather than continuously reading and sending blobs, ignoring client responses, the handler will only read and send additional print data when the client acknowledges that it is ready.
**NOTE:** This was originally opened as #15, but with the wrong JIRA issue tag.
> GUACAMOLE-44: Refactor the RDPDR printer to synchronous operation.

- src/protocols/rdp/rdp_settings.c
- src/protocols/rdp/rdp_settings.h
- src/protocols/rdp/user.c
- src/protocols/ssh/settings.c
- src/protocols/ssh/settings.h
- src/protocols/ssh/user.c
- src/protocols/telnet/settings.c
- src/protocols/telnet/settings.h
- src/protocols/telnet/user.c
- src/protocols/vnc/user.c
Previously, the only protocol providing a "read-only" parameter was VNC, as VNC servers inherently support screen sharing. Now that Guacamole supports screen sharing regardless of underlying protocol, such parameters should be provided across the board.
This change adds a "read-only" parameter to the RDP, SSH, and telnet protocols, and extends the existing "read-only" parameter of VNC to be handled on a per-user (rather than per-connection) basis.
> GUACAMOLE-5: Add per-user "read-only" parameter to all protocols.

- src/protocols/rdp/Makefile.am
- src/protocols/rdp/client.c
- src/protocols/rdp/input.c
- src/protocols/rdp/input.h
- src/protocols/rdp/keyboard.c
- src/protocols/rdp/keyboard.h
- src/protocols/rdp/rdp.c
- src/protocols/rdp/rdp.h
Finishing the RDP portion of [GUACAMOLE-51](https://issues.apache.org/jira/browse/GUACAMOLE-51) is getting a bit hairy since the keymap structures are interwoven with the rest of the RDP client code. Really shouldn't have done it that way.
This change moves the main keymap-driven keyboard translation code into its own files and structures, centered around the `guac_rdp_keyboard` abstraction.
> GUACAMOLE-51: Separate RDP keyboard handling into dedicated files / structures.

- bin/guacctl
- configure.ac
- doc/Doxyfile
- src/guacd/man/guacd.8
- src/guacd/man/guacd.conf.5
- src/guacenc/man/guacenc.1
- src/libguac/Makefile.am
The Dockerfile is untouched because it needs more work before the release; simply bumping the version numbers in it would be insufficient.
> GUACAMOLE-87: Bump guacamole-server version numbers to 0.9.10-incubating.

- src/guacd-docker/README.md
Beware that this does contain references to Docker images which do not yet exist. Those images will exist post-release.
> GUACAMOLE-97: Update guacd Docker README.md with respect to Apache.

- src/protocols/rdp/rdp.c
From [GUACAMOLE-117](https://issues.apache.org/jira/browse/GUACAMOLE-114):
>
> Commit a64c3e0 from [GUACAMOLE-34](https://issues.apache.org/jira/browse/GUACAMOLE-34) added several calls to `guac_client_stop()`, one of which runs in all cases after the connection has closed, even if that closure is due to the need to handle a resize.
>
> `guac_client_stop()` should not be invoked in that case. It should only be invoked when the connection absolutely must terminate.
>
> GUACAMOLE-117: Do not stop connection when the intent is to reconnect.

- src/guacd/socket-ssl.c
- src/libguac/socket-fd.c
- src/protocols/rdp/client.h
- src/protocols/rdp/rdp.c
- src/protocols/ssh/ssh.c
- src/protocols/telnet/telnet.c
- src/terminal/terminal.c
In most cases, this was an extremely simple change. The change for RDP was slightly more complex, as an RDP connection may involve many file descriptors. The form of the change should nonetheless look familiar.
Beware that I had to reformat RDP's "wait for messages" function somewhat, such that the behavior of the function could be more easily verified.
> GUACAMOLE-118: Use poll() instead of select()

- doc/Doxyfile
- src/guacd/man/guacd.8
- src/guacd/man/guacd.conf.5
- src/guacenc/man/guacenc.1
- src/protocols/rdp/Makefile.am
Generated sources were not properly excluded from the source tarball, and Apache license comments were missing from:
1. The `Doxyfile` for libguac
2. The manpage source for guacenc, guacd, and guacd.conf
> GUACAMOLE-119: Add missing Apache license comments. Exclude generated source.

- Makefile.am
From @justinmclean regarding the [0.9.10-incubating (RC2) release vote](http://mail-archives.apache.org/mod_mbox/incubator-general/201612.mbox/%3CB6E93324-682C-4690-966B-EC0A4E39DDFE%40classsoftware.com%3E):
>
> Sorry but it’s -1 binding as the server artefact is missing a DISCLAIMER and NOTICE file.
>
These files are missing from the source .tar.gz because they are not specified within `EXTRA_DIST` of the top-level `.Makefile.am`. Also missing is `CONTRIBUTING`, along with everything Docker-related.
> GUACAMOLE-143: Add missing files to EXTRA_DIST

- README
From @justinmclean regarding the [0.9.10-incubating (RC2) release vote](http://mail-archives.apache.org/mod_mbox/incubator-general/201612.mbox/%3CB6E93324-682C-4690-966B-EC0A4E39DDFE%40classsoftware.com%3E):
>
> When configuring the server I get this error:
> 
>     configure: error: "libpng is required for writing png messages"
> 
> But I do have libpng installed:
> 
>     brew install libpng
>     Warning: libpng-1.6.26 already installed
> 
> Is OSX a supported platform? It would be nice if the README had a bit more information on how to compile and what the dependancies are. For instance I think the instruction "Before compiling, you need to have compiled and installed libguac, the core Guacamole library” may possibly be misleading?
>
These changes update the `README` to more …
> GUACAMOLE-145: Update README to include (correct) required and optional dependencies.

- src/libguac/user-handlers.c
- src/protocols/rdp/rdp.c
- src/protocols/vnc/vnc.c
This change modifies the lag calculations provided by libguac and used within the VNC and RDP protocols such that:
* Server processing time is excluded
* Bad client timestamps are ignored
> GUACAMOLE-172: Improve/fix processing lag calculations

- src/terminal/terminal.h
- src/terminal/terminal_handlers.c
Terminal emulators maintain the scrolling region and the bounds of the terminal separately. Console codes which allow the scrolling region to be redefined facilitate utilities like top, tmux, or screen which must maintain control of what scrolls and what doesn't.
Guacamole handles scrolling improperly, automatically scrolling whenever the cursor exceeds the bounds of the scroll region. This is only correct behavior when the cursor is within the scrolling region. The terminal should not be scrolled *at all* when the cursor is outside the scrolling region. If outside the scrolling region, the cursor should simply be kept within terminal bounds.
> GUACAMOLE-148: Fix handling of terminal scroll.

- src/protocols/rdp/rdp_fs.c
- src/protocols/rdp/rdp_fs.h
glibc has taken it upon themselves to flag `readdir_r()` as deprecated in advance of any official change to POSIX. This breaks the guacamole-server build for any environment with a sufficiently-recent glibc.
It should be safe to use `readdir()` as multiple threads will not be accessing the same directory stream. From the glibc manpage for `readdir_r()`:
> In the current POSIX.1 specification (POSIX.1-2008), readdir(3) is not required to be thread-safe. However, in modern implementations (including the glibc implementation), concurrent calls to readdir(3) that specify different directory streams are thread-safe. Therefore, the use of readdir_r() is generally unnecessary in multithreaded programs.
> GUACAMOLE-94: Use readdir() instead of readdir_r().

- src/protocols/rdp/guac_rdpsnd/rdpsnd_messages.c
If this is not done, the format count and indices will mismatch each time a new SNDC_FORMATS PDU is received from the RDP server, and further streaming of audio will fail. Older versions of Windows will only set the formats once, but Windows Server 2016 does this multiple times.
> GUACAMOLE-218: Reset internal RDPSND audio format counter whenever a new SNDC_FORMATS PDU is received.

- src/guacenc/ffmpeg-compat.c
From [doc/APIchanges](https://github.com/FFmpeg/FFmpeg/blob/n3.1/doc/APIchanges#L40-L43):
2016-04-21 - 7fc329e - lavc 57.37.100 - avcodec.h
Add a new audio/video encoding and decoding API with decoupled input
and output -- avcodec_send_packet(), avcodec_receive_frame(),
avcodec_send_frame() and avcodec_receive_packet()
We should be using the older API for anything older than 57.37.100, which does include the version currently in Ubuntu 16.10.
> GUACAMOLE-217: Do not use FFmpeg's decoupled I/O functions if libavcodec older than 57.37.100.

- src/protocols/rdp/rdp.c
- src/protocols/vnc/vnc.c
Freeing the SFTP user immediately after an init failure results in the user being freed twice: first within the init routine when the failure occurs, and again within the client free handler. Since the client free handler is always invoked, it makes sense to rely on that function alone to handle the cleanup.
> GUACAMOLE-194: Free SSH user for VNC+SFTP and RDP+SFTP only once.

- configure.ac
- src/common-ssh/Makefile.am
- src/common-ssh/buffer.c
- src/common-ssh/common-ssh/buffer.h
- src/common-ssh/common-ssh/dsa-compat.h
- src/common-ssh/common-ssh/rsa-compat.h
- src/common-ssh/dsa-compat.c
- src/common-ssh/key.c
- src/common-ssh/rsa-compat.c
- src/common-ssh/ssh.c
- src/guacd/daemon.c
This change updates guacamole-server to the OpenSSL 1.1 API, with backward-compatible shims for things which are not otherwise compatible.
> GUACAMOLE-205: Update to OpenSSL 1.1 API

- src/common/surface.c
All layers are fully opaque by default, and `guac_common_surface` should accurately represent this. Doing otherwise means that newly-joining users of a shared connection will receive the wrong layer opacity, effectively hiding all but the default layer.
> GUACAMOLE-226: Properly initialize new layers as fully opaque.

- src/common/common/cursor.h
- src/common/cursor.c
- src/libguac/guacamole/protocol.h
- src/libguac/protocol.c
- src/terminal/terminal.c
This change adds a new "mouse" instruction which reports the current location of the mouse cursor to all users not actively moving the mouse, allowing the client to handle rendering of the shared cursor (rather than relying on the server to render the cursor itself).
> GUACAMOLE-231: Report server-side mouse position using "mouse" instruction.

- src/pulse/pulse.c
To avoid this sort of problem going forward, this change also adds long-missing documentation for the PulseAudio callbacks being used.
> GUACAMOLE-240: Always pass guac_pa_stream to PulseAudio callbacks.

- src/libguac/timestamp.c
Fix disconnects due to back ward running time. Fix by using CLOCK_MONOTONIC.
Fix: https://issues.apache.org/jira/browse/GUACAMOLE-239
> GUACAMOLE-239: When available, use CLOCK_MONOTONIC to prevent backwards running time

- src/guacd/conf-args.c
- src/guacd/conf-file.c
- src/guacd/conf-parse.c
- src/guacd/log.c
- src/guacd/man/guacd.8
- src/guacd/man/guacd.conf.5
- src/libguac/guacamole/client-types.h
We've avoided adding log levels below DEBUG, as syslog does not support such levels, but as a consequence we are forced to avoid logging which may affect performance, useful though it may be.
This change adds a new TRACE log level to libguac's existing logging facilities, allowing logging of low-level events (like those required by [GUACAMOLE-259](https://issues.apache.org/jira/browse/GUACAMOLE-259)) which would otherwise pollute use of the DEBUG level.
> GUACAMOLE-259: Add TRACE log level.

- configure.ac
- src/protocols/rdp/rdp_settings.c
- src/protocols/rdp/rdp_settings.h
FreeRDP 1.1 and later have support for remote desktop gateways. This change adds connection parameters for the settings which enable/configure that support.
> GUACAMOLE-40: Add support for RD gateway.

- src/common/surface.c
From [GUACAMOLE-282](https://issues.apache.org/jira/browse/GUACAMOLE-282):
>
> The common surface implementation used within guacamole-server is incorrect with respect to binary transfer functions as of [GUACAMOLE-188](https://issues.apache.org/jira/browse/GUACAMOLE-188), which added support for the alpha channel to the common surface.
>
> Prior to [GUACAMOLE-188](https://issues.apache.org/jira/browse/GUACAMOLE-188), the common surface supported only the red, green, and blue channels, thus simple binary operations correctly mirrored those of the JavaScript Guacamole client.
>
> After [GUACAMOLE-188](https://issues.apache.org/jira/browse/GUACAMOLE-188), the contents of a surface might have alpha channel values, which are not supposed to be taken into account for all transfer functions. The …
> GUACAMOLE-282: Correct common surface transfer functions to copy/ignore alpha channel as required.

- src/protocols/rdp/rdp_fs.c
From [GUACAMOLE-326](https://issues.apache.org/jira/browse/GUACAMOLE-326):
> When a file has been downloaded over the internet via Windows 10, and that file is later transferred over Guacamole using the magic "Download" folder, multiple files end up being transferred: "filename.ext" and "filename.ext:ZoneIdentifier".
>
> This is due to the way Windows 10 tags files downloaded over the internet with secondary "streams", such that it can warn users of the risks prior to executing those files:
>
> http://stackoverflow.com/questions/4496697/what-is-zone-identifier
>
> As Guacamole does not actually use such files, and the underlying filesystem does not support them, they should be appropriately ignored/rejected rather than downloaded.
> GUACAMOLE-326: Explicitly deny attempted reads/writes to Windows named data streams.

- src/common-ssh/common-ssh/sftp.h
- src/common-ssh/sftp.c
- src/protocols/rdp/rdp.c
- src/protocols/rdp/rdp_settings.c
- src/protocols/rdp/rdp_settings.h
- src/protocols/ssh/settings.c
- src/protocols/ssh/settings.h
- src/protocols/ssh/ssh.c
- src/protocols/vnc/settings.c
- src/protocols/vnc/settings.h
- src/protocols/vnc/vnc.c
This change adds a new "sftp-root-directory" parameter to VNC, RDP, and SSH which defines the root directory exposed via Guacamole's file browser. Some care is taken to ensure that requests outside this root directory cannot be made via the file browse, in that both the root directory and the requested filename are normalized prior to being concatenated.
> GUACAMOLE-303: Allow root directory of SFTP filesystem to be configured.

- configure.ac
- src/common/recording.c
- src/libguac/Makefile.am
- src/libguac/guacamole/socket-wsa.h
- src/libguac/socket-fd.c
- src/libguac/socket-ssl.c
- src/libguac/socket-wsa.c
- src/libguac/wait-fd.c
- src/libguac/wait-fd.h
This change brings Windows compatibility back to the libguac portion of the guacamole-server build, allowing it to be built with the [MinGW](http://www.mingw.org/) toolchain, so long as libguac's normal dependencies are also available, as well as Windows ports of:
* libdl
* libpthread
This change also adds a Windows Socket API (WSA, also known as "winsock") implementation of `guac_socket`, allowing Windows applications to be implemented which leverage libguac to serve Guacamole protocol directly.
> GUACAMOLE-325: Restore Windows-compatibility at libguac level.

- src/guacd/conf-file.c
- src/protocols/rdp/rdp_cliprdr.c
- src/terminal/display.c
[src/guacd/conf-file.c:206]: (error) Memory leak: conf
[src/protocols/rdp/rdp_cliprdr.c:205]: (error) Memory leak: output
[src/terminal/display.c:283]: (error) Memory leak: display
[src/terminal/display.c:290]: (error) Memory leak: display
> GUACAMOLE-383: resolve issues identified by cppcheck

- src/common-ssh/ssh.c
Quick fix to correct a memory leak identified by the latest Coverity scan in the common ssh code.
> GUACAMOLE-398: Fix memory leak identified by Coverity

- src/protocols/ssh/ssh.c
Root Cause:
In the ssh library of guacd, function ssh_client_thread(), when guac_ssh_get_user() fails to load private key for ssh authentication, it will return NULL. In this case, the subsequent call to guac_common_ssh_create_session() with parameter 'user=0x0' will cause guacd crash in function guac_common_ssh_authenticate() by accessing 'user->username'.
Solution:
In guac_common_ssh_create_session(), validate parameter 'user'. If it is NULL, abort the ssh session.
Reviewed the logic for other parameters of the function, they look okay and no need to be validated at this point.
Test:
- configured a ssh app with an encrypted private key and a wrong passphrase.
- ran the ssh app from web portal and observed guacd crash.
- applied the fix and reran the ssh app. Observed no crash.
> GUACAMOLE-400: Fix guacd crash when ssh key fails

- src/libguac/Makefile.am
- src/protocols/rdp/Makefile.am
Use $(srcdir) in places were it's needed, so that an out-of-tree build works.
> GUACAMOLE-402: fix out-of-tree build

- src/guacd/move-fd.c
Fixed valgrind's complaints when sending fds.
```
==8081== Thread 2:
==8081== Syscall param sendmsg(msg.msg_control) points to uninitialised byte(s)
==8081==    at 0x505EA6D: ??? (syscall-template.S:84)
==8081==    by 0x403F5C: guacd_send_fd (move-fd.c:61)
==8081==    by 0x40390A: guacd_add_user (connection.c:196)
==8081==    by 0x40390A: guacd_route_connection (connection.c:311)
==8081==    by 0x40390A: guacd_connection_thread (connection.c:393)
==8081==    by 0x50556B9: start_thread (pthread_create.c:333)
==8081==    by 0x5A1F3DC: clone (clone.S:109)
==8081==  Address 0xa558d54 is on thread 2's stack
==8081==  in frame #1, created by guacd_send_fd (move-fd.c:34)
==8081==  Uninitialised value was created by a stack allocation
==8081==    at 0x403ED0: guacd_send_fd (move-fd.c:34)
==8081== …
```
> GUACAMOLE-411: Fixed using uninitialized values in guacd_send_fd

- configure.ac
- src/protocols/rdp/Makefile.am
This is a very minor tweak to the configure.ac file that adds the winpr-utils library to the list of libraries linked when the winpr/stream.h file is found.  This works correctly for FreeRDP 1.0 (winpr/stream.h is not present) and FreeRDP 1.1 (winpr/stream.h is present), but probably not FreeRDP 2.0, as winpr libraries got significantly collapsed there.  But, I think there may be other issues with FreeRDP 2.0 and the Guacamole server.
> GUACAMOLE-296: Fix linking issue that causes audio issues with FreeRDP 1.1

- configure.ac
- src/protocols/rdp/Makefile.am
Reverts manual changes made to the RDP protocol Makefile.am to add in winpr-utils, which now seems to be linking automatically.
> GUACAMOLE-296: Revert manual addition of winpr-utils library.

- src/guacenc/instruction-size.c
When running the guacenc utility against Guacamole session recordings, the following warning is sometimes repeatedly printed while the video is encoded:
guacenc: WARNING: Layer index out of bounds: -1
This warning is coming from `guacenc_display_get_layer()`, a function used within guacenc to retrieve the layer for a given index, within guacenc's implementation of the "size" instruction. Because the "size" instruction can apply to both buffers and layers, calling `guacenc_display_get_layer()` is incorrect. We should instead use `guacenc_display_get_related_buffer()`, which can deal with both buffers and layers.
> GUACAMOLE-307: The "size" instruction can also apply to buffers, not just layers.

- src/protocols/rdp/Makefile.am
- src/protocols/rdp/keymaps/tr_tr_qwerty.keymap
I've created tr_tr_qwerty.keymap according to Turkish Q keyboard layout. I have tested this over FreeRDP with a Windows machine, everything seems to be working fine.
> GUACAMOLE-481: Add Turkish Q keymap for RDP

- .dockerignore
- Dockerfile
- src/guacd-docker/bin/build-guacd.sh
Since Docker CE 17.05 (edge) and 17.06 (stable), multi-stage builds can be used to create images using a different base images for build versus runtime. This will simplify the process of creating a runtime image for guacamole-server, and will improve build times by making much better use of  Docker's image layer cache.
> GUACAMOLE-456: use Docker multi-stage build

- src/protocols/rdp/rdp.c
This change shifts the RDP disconnect handling logic down such that the disconnect reason code is always checked if `freerdp_shall_disconnect()` reports that an orderly disconnect is occurring. `GUAC_PROTOCOL_STATUS_UPSTREAM_UNAVAILABLE` is still used for lower-level failures (where it is correct).
> GUACAMOLE-484: Ensure disconnect reason code is checked for orderly RDP disconnect.

- src/protocols/ssh/client.c
- src/protocols/ssh/ssh.c
- src/terminal/terminal.c
- src/terminal/terminal/terminal.h
Root Cause:
See the core dump and Valgrind report posted on Jira. guacd was reading a ssh terminal which had been freed. When a ssh connection is terminated, guac_ssh_client_free_handler() will be called from guacd_exec_proc() -> guac_client_free() with pointer client->free_handler. In guac_ssh_client_free_handler(), when ssh_client->term is freed, ssh_client->client_thread may still be using the ssh_client->term. It causes the crash reported in this bug.
The stack trace exposing the problem can be found by running guacd under Valgrind with a ssh test script. The test script repeats doing ssh login and logout for 5000 times.
Solution:
In guac_ssh_client_free_handler(), before calling guac_terminal_free(ssh_client->term), close the stdin pipe of the terminal to stop reading the pipe with …
> GUACAMOLE-384: fixing segfault during ssh disconnect

- src/protocols/rdp/Makefile.am
- src/protocols/rdp/decompose.c
- src/protocols/rdp/decompose.h
- src/protocols/rdp/keyboard.c
- src/protocols/rdp/keyboard.h
This change leverages the existing mapping of dead keys within Guacamole's RDP keymaps to type using dead keys as necessary within the remote desktop, even though Guacamole will not receive key events for dead keys itself.
If the RDP layout lacks a specific key for a key pressed by the user, Guacamole will now try to decompose that key into its corresponding dead and base keys. If this succeeds, and both the dead key and base key are defined within the RDP keyboard layout, then the key is typed within the remote desktop using the dead and base keys. If typing the key is impossible through any other mechanism, Guacamole will still resort to using Unicode events.
> GUACAMOLE-352: Add support for typing using dead keys within RDP.

- src/protocols/rdp/keyboard.c
- src/protocols/rdp/keyboard.h
- src/protocols/rdp/rdp_keymap.h
Historically, Guacamole's RDP support has used macros to read and write key definitions within keymaps and similar structures. These macros are difficult to read, difficult to verify, and frequently result in false positives in static analysis builds due to the way each keysym is mapped.
This change replaces these macros with well-documented functions, as well as a more straightforward and explicit mapping scheme. Internal storage of the keymap and current key state has also been unified such that only one set of functions is necessary to address both.
> GUACAMOLE-352: Clean up keymap lookup/update logic for sake of verifiability.

- src/guaclog/keydef.c
The `modifier` flag for `guaclog_keydef` is not properly initialized in all cases. If ever the associated memory is not already zeroed out, this could lead to incorrect interpretation of events.
> GUACAMOLE-313: Properly initialize modifier flag for all keydefs.

- src/common/common/recording.h
- src/common/recording.c
- src/libguac/guacamole/protocol.h
- src/libguac/protocol.c
- src/protocols/rdp/input.c
- src/protocols/rdp/rdp.c
- src/protocols/rdp/rdp_settings.c
- src/protocols/rdp/rdp_settings.h
- src/protocols/ssh/input.c
- src/protocols/ssh/settings.c
- src/protocols/ssh/settings.h
- src/protocols/ssh/ssh.c
- src/protocols/telnet/input.c
- src/protocols/telnet/settings.c
- src/protocols/telnet/settings.h
- src/protocols/telnet/telnet.c
- src/protocols/vnc/input.c
- src/protocols/vnc/settings.c
- src/protocols/vnc/settings.h
- src/protocols/vnc/vnc.c
This change adds a set of flags which control the contents of session recordings, allowing key events to be included if the associated flag is explicitly set. Due to clear privacy concerns, key events are *not* included by default.
Parts of session recordings which *are* included by default, like graphical updates and mouse events, can also now be explicitly disabled if desired.
> GUACAMOLE-313: Add support for including key events within session recordings.

- src/protocols/rdp/rdp_settings.c
- src/protocols/rdp/rdp_settings.h
This change adds support for disabling bitmap caching and offscreen caching, which are enabled by FreeRDP by default.
> GUACAMOLE-448: Add support for configuring bitmap caching.

- src/protocols/rdp/guac_rdpdr/rdpdr_messages.c
- src/protocols/rdp/rdp_settings.c
This change passes through the configured client_name in the RDP redirect messages, which tweaks how Windows shows redirected drives (Share on client_name) and printers (client_name: PRN1 in port settings).
> GUACAMOLE-523: Use client_name for redirect messages

- Dockerfile
Small changes to allow the guacd log level to be passed through as an environment variable.  Not entirely sure this is the right way to go - I know the guacamole-client code for taking and parsing variables is significantly more complex.
> GUACAMOLE-42: Add support for specifying log level to guacd in docker

- src/guacd/proc.c
- src/guacd/proc.h
This change refactors guacd such that `guac_client_free()` is invoked in a dedicated thread, while guacd waits for the free/disconnect operation to signal completion. If free/disconnect does not complete in a timely manner, guacd takes control, forcibly kills the connection process, and logs a warning.
In addition, even if the `guac_client` is freed successfully and within a reasonable time, guacd now verifies that all child processes of that connection have also terminated. If any child processes remain, they are forcibly terminated by guacd, and a warning is logged.
> GUACAMOLE-533: Wait at most 5 seconds for connection processes to terminate following disconnect.

- Dockerfile
- src/guacd-docker/bin/build-guacd.sh
- src/guacd-docker/bin/link-freerdp-plugins.sh
- src/guacd-docker/bin/list-dependencies.sh
These changes migrate from a CentOS-based image to a Debian-based one, updating dependencies accordingly.
Part of the idea behind this migration is to allow the Docker image to be easily rebuilt to take advantage of upstream updates, thus rather than hard-code runtime dependencies, the image now dynamically determines the packages required by listing the packages which provide the libraries that end up linked.
> GUACAMOLE-407: Refactor guacd Docker image to use "debian:stable" base.

- src/protocols/ssh/settings.c
- src/protocols/ssh/settings.h
- src/protocols/ssh/ssh.c
- src/protocols/telnet/settings.c
- src/protocols/telnet/settings.h
- src/protocols/telnet/telnet.c
Add a terminal-type parameter for SSH and Telnet connections, to specify the terminal emulator type that is passed to programs. If not specified, the default type of "linux" is used in keep with existing behavior.
Some programs make use of the terminal type to determine some of the terminal's capabilities. For example, tmux seems to only have good 256-color support when the terminal type is something like `screen-256color` instead of `linux`.
> GUACAMOLE-565: Add terminal-type parameter for SSH and Telnet.

- src/protocols/ssh/settings.c
- src/protocols/telnet/settings.c
- src/terminal/display.c
- src/terminal/named-colors.c
- src/terminal/terminal.c
- src/terminal/terminal/display.h
- src/terminal/terminal/terminal.h
- src/terminal/xparsecolor.c
Change the "color-scheme" parameter into a series of semicolon-separated name-value pairs, so that individual terminal colors can be configured. For example, this configuration changes the terminal to use a "solarized light" color scheme:
<param name="color-scheme">
background: rgb:fd/f6/e3;
foreground: rgb:65/7b/83;
color0:     rgb:07/36/42;
color8:     rgb:00/2b/36;
color1:     rgb:dc/32/2f;
color9:     rgb:cb/4b/16;
color2:     rgb:85/99/00;
color10:    rgb:58/6e/75;
color3:     rgb:b5/89/00;
color11:    rgb:65/7b/83;
color4:     rgb:26/8b/d2;
color12:    rgb:83/94/96;
color5:     rgb:d3/36/82;
color13:    rgb:6c/71/c4;
color6:     rgb:2a/a1/98;
color14:    rgb:93/a1/a1;
color7:     rgb:ee/e8/d5;
color15:    rgb:fd/f6/e3;
</param>
Backward compatibility is preserved by translating …
> GUACAMOLE-470: Make terminal colors configurable through "color-scheme" parameter

- src/terminal/terminal/terminal_handlers.h
- src/terminal/terminal_handlers.c
I see some programs emitting these sequences. An APC escape sequence contains an arbitrary string command between (ESC _) and (ESC \) sequences. While we don't support any APC commands, we
should ignore any commands that we do encounter so they're not echoed onto the screen.
> GUACAMOLE-564: Hide APC escape sequence.

- src/terminal/terminal.c
Older versions of GCC (prior to 5.1) emits an "incompatible pointer type" warning when passing `foo(*)[]` as `const foo(*)[]`. This was changed in GCC 5.1, and this patch adds explicit casts to remove the warning under older GCC.
> GUACAMOLE-470: Fix incompatible pointer type warning under older GCC

- src/protocols/ssh/Makefile.am
- src/protocols/ssh/pipe.c
- src/protocols/ssh/pipe.h
- src/protocols/ssh/user.c
- src/protocols/telnet/Makefile.am
- src/protocols/telnet/pipe.c
- src/protocols/telnet/pipe.h
- src/protocols/telnet/user.c
- src/terminal/Makefile.am
- src/terminal/terminal-stdin-stream.c
- src/terminal/terminal.c
- src/terminal/terminal/terminal.h
This change adds support to SSH and telnet for reading user input from a pipe stream named "STDIN". When the client side opens this pipe stream, user input through keyboard, clipboard, etc. is blocked, and data from the pipe stream is sent directly over the SSH/telnet connection. User input is unblocked once the "STDIN" pipe is closed.
> GUACAMOLE-574: Allow input for SSH/telnet to come from "STDIN" pipe.

- src/protocols/rdp/guac_rdpdr/rdpdr_fs_service.c
- src/protocols/rdp/guac_rdpdr/rdpdr_messages.c
- src/protocols/rdp/guac_rdpdr/rdpdr_messages.h
- src/protocols/rdp/guac_rdpdr/rdpdr_printer.c
- src/protocols/rdp/guac_rdpdr/rdpdr_printer.h
- src/protocols/rdp/guac_rdpdr/rdpdr_service.c
- src/protocols/rdp/guac_rdpdr/rdpdr_service.h
- src/protocols/rdp/rdp_settings.c
- src/protocols/rdp/rdp_settings.h
This adds the parameters and changes to rdpdr to make the printer name configurable in the RDP session.
I'm not sure if we had totally settled in the JIRA issue on whether or not this change was actually going to happen, but I went ahead and did it.  I can close the PR if we decide against it.
> GUACAMOLE-445: Make Printer Name Configurable

- src/protocols/rdp/guac_rdpdr/rdpdr_fs_messages_vol_info.c
- src/protocols/rdp/guac_rdpdr/rdpdr_fs_service.c
- src/protocols/rdp/guac_rdpdr/rdpdr_fs_service.h
- src/protocols/rdp/guac_rdpdr/rdpdr_messages.h
- src/protocols/rdp/guac_rdpdr/rdpdr_service.c
- src/protocols/rdp/rdp_settings.c
- src/protocols/rdp/rdp_settings.h
Allows for the name of the redirected drive to be configured when pushing a filesystem through via RDP.
Note that this change not only allows for the name to be configured, but also *removes UTF-16 encoding* of the drive name as it appears that Windows does not expect the filesystem name to be UTF-16 encoded.
> GUACAMOLE-446: Allow redirected drive name to be configured

- src/terminal/buffer.c
- src/terminal/select.c
- src/terminal/terminal/buffer.h
The new bounds checks added for copying text from the scrollback buffer are incorrect for the case where the number of rows in scrollback has not yet reached at least the size of the terminal window. These changes remove those incorrect checks, instead modifying scrollback buffer row retrieval such that it is guaranteed to stay within bounds.
> GUACAMOLE-573: Correct scrollback buffer bounds checks.

- src/terminal/terminal.c
- src/terminal/terminal/terminal.h
- src/terminal/terminal_handlers.c
As described on [GUACAMOLE-597](https://issues.apache.org/jira/browse/GUACAMOLE-597), these changes add an optional "flags" parameter to the existing OSC that redirects terminal output to a pipe stream. In addition to the old sequence, the following sequence may now be used:
`ESC` `]` `482202` `;` `FLAGS` `;` `NAME` `ST`
where `FLAGS` is the bitwise OR of any or all of the following flags:
Value | Description
----- | -----------
1     | Send output to both the pipe stream *and* the user's display. By default, output will be sent to only the pipe stream for as long as the pipe stream is open.
2     | Automatically flush the pipe stream when a frame would be rendered, only buffering data between frames. By default, data sent to the pipe stream is buffered until the buffer is full (roughly …
> GUACAMOLE-597: Add optional flags to OSC for controlling redirected terminal output.

- src/common/clipboard.c
- src/common/common/clipboard.h
- src/protocols/ssh/client.c
- src/protocols/ssh/client.h
- src/protocols/ssh/clipboard.c
- src/protocols/ssh/ssh.c
- src/protocols/ssh/ssh.h
- src/protocols/telnet/client.c
- src/protocols/telnet/client.h
- src/protocols/telnet/clipboard.c
- src/protocols/telnet/telnet.c
- src/protocols/telnet/telnet.h
- src/terminal/terminal.c
- src/terminal/terminal/terminal.h
As of recent changes due to [GUACAMOLE-559](https://issues.apache.org/jira/browse/GUACAMOLE-559), there is a random change that SSH or telnet connections will segfault while the connection is being established. This is due to a race condition between the receipt of initial clipboard data from the client (which happens after the first frame is received) and the assignment of the terminal to the server-side client structure (which happens within a thread). Since the clipboard contents are maintained by the terminal, the structure receiving the new clipboard data may not be accessible at the time the data is received.
These changes:
1. Remove maintenance of the clipboard from the terminal, instead requiring that the protocol implementation provide its own `guac_common_clipboard` instance …
> GUACAMOLE-559: Fix race condition in receipt of clipboard data by terminal.

- bin/guacctl
- src/protocols/ssh/settings.c
- src/protocols/ssh/settings.h
- src/protocols/ssh/ssh.c
- src/protocols/telnet/settings.c
- src/protocols/telnet/settings.h
- src/protocols/telnet/telnet.c
- src/terminal/terminal.c
- src/terminal/terminal/terminal.h
- src/terminal/terminal/terminal_handlers.h
- src/terminal/terminal_handlers.c
These changes allow the scrollback buffer size for SSH and telnet to be changed through two mechanisms:
1. A new connection parameter (`scrollback`) which sets the initial scrollback size and functions as an upper limit.
2. A new Guacamole-specific console code which requests the scrollback size be changed. The terminal emulator may ignore this value if the upper limit set via connection parameters is lower than the requested value, or if the size of the terminal requires additional buffer space. The `guacctl` utility has been modified to provide a `-S` option to allow the console code to be sent conveniently.
It's important to note that, like other terminal emulators, the Guacamole terminal emulator uses the same buffer space to back the active display area and the off-screen region …
> GUACAMOLE-610: Add support for changing scrollback buffer size.

- src/terminal/named-colors.c
Named colors don't currently work inside the color-scheme configuration, because `guac_terminal_named_color_search` expects the name string to be null-terminated, whereas we work with non-null-terminated strings when parsing the color scheme.
To make named colors work, we can either copy the name string to a separate null-terminated buffer, or we can make `guac_terminal_named_color_search` support non-null-terminated strings. This patch implements the latter option, and makes `guac_terminal_named_color_search` treat semi-colons as string terminators.
> GUACAMOLE-470: Support named colors in color-scheme configuration.

- src/protocols/ssh/ssh.c
- src/protocols/telnet/settings.c
- src/protocols/telnet/settings.h
- src/protocols/telnet/telnet.c
- src/terminal/terminal-stdin-stream.c
- src/terminal/terminal.c
- src/terminal/terminal/terminal.h
These changes add a new function, `guac_terminal_start()`, which must be called before the terminal emulator will send the `sync` messages which define frame boundaries. SSH and telnet have been modified to call this function only when the connection has actually been successful.
By withholding frames until the underlying connection is complete, the "Connected. Waiting for response..." status notification becomes an accurate reflection of the connection state. In addition, server-side handling of connection errors via `FailoverGuacamoleSocket` becomes possible, as the instruction filtering code that searches for errors also uses that first `sync` as a sign of success.
As telnet does define an authentication mechanism, there is no standard way to detect whether authentication has …
> GUACAMOLE-622: Withhold first SSH/telnet frame until connection is verified

- src/libguac/guacamole/user-fntypes.h
- src/libguac/guacamole/user.h
- src/libguac/user-handlers.c
- src/libguac/user-handlers.h
This is the non-handshake portion of changes which allow connection parameters to be sent via streams, rather than as elements of a single, handshake-only instruction. The expected flow is as follows:
1. While the connection is underway, the connected client may begin to stream an update to a connection parameter using an `argv` instruction. It is expected that not all parameters may be updated in this manner, that some updates will be refused for security reasons, and even that instruction filtering within the webapp may intercept the inbound stream and apply additional constraints.
2. If the underlying protocol supports updating that particular parameter, this will be indicated with a successful `ack`. If the parameter cannot be updated, either due to lack of support or the parameter …
> GUACAMOLE-629: Add support for updating connection parameters of in-progress connections.

- Makefile.am
The `src/protocols/kubernetes` directory needs to be present in `DIST_SUBDIRS` for the source of the Kubernetes plugin to be included in the .tar.gz file built by `make dist`.
The "guacamole-server-master" build in Jenkins verifies that the .tar.gz built by `make dist`, so this is [currently failing](https://builds.apache.org/view/E-G/view/Guacamole/job/guacamole-server-master/67/console):
```
...
configure: creating ./config.status
config.status: creating Makefile
config.status: creating doc/Doxyfile
config.status: creating tests/Makefile
config.status: creating src/common/Makefile
config.status: creating src/common-ssh/Makefile
config.status: creating src/terminal/Makefile
config.status: creating src/libguac/Makefile
config.status: creating src/guacd/Makefile
config.status: creating …
```
> GUACAMOLE-623: Include Kubernetes plugin in dist directories.

- configure.ac
- src/protocols/kubernetes/kubernetes.c
- src/protocols/kubernetes/ssl.c
The build is currently broken on CentOS 7 with EPEL, where libwebsockets is available but at version 1.7.5. Several differences are in play which needed to be addressed here:
* SSL client initialization flags do not exist. Instead, a set of documented integer values is used for no SSL (0), SSL with verification of certificate (1), and SSL which allows self-signed certificates (2). The latter is unfortunately very specific to self-signed certificates, leading to verification failures in other cases - more on that below.
* The `lws_callback_http_dummy()` function which must be invoked within the event callback to perform some sort of housekeeping tasks internal to libwebsockets is not defined. The event callback is instead expected to simply return 0.
* The `pwsi` member of the …
> GUACAMOLE-623: Fix build against older libwebsockets.

- src/protocols/vnc/settings.c
Corrects the order of parameters in the VNC settings that I believe was causing issues with VNC known host checking (and probably other items).
> GUACAMOLE-527: Correct order of SFTP parameters in VNC.

- src/protocols/ssh/argv.c
- src/protocols/telnet/argv.c
- src/terminal/display.c
- src/terminal/terminal.c
- src/terminal/terminal/display.h
- src/terminal/terminal/terminal.h
These changes build off of the changes from #198, additionally allowing the font name and size to be changed while the connection is running. The terminal is redrawn and resized as necessary to take the new font into account.
> GUACAMOLE-630: Allow font parameters of active SSH/telnet session to be changed.

- src/protocols/rdp/rdp.c
- src/protocols/rdp/rdp_settings.c
- src/protocols/rdp/rdp_settings.h
- src/protocols/ssh/settings.c
- src/protocols/ssh/settings.h
- src/protocols/ssh/ssh.c
These are the server-side changes necessary to support timezone redirection for RDP and SSH.  I originally attempted to implement for Telnet, as well; however, I quickly found that at least the default Linux telnet server implementation completely ignores arbitrary environment variables and only pays attention to specific ones (USER, REMOTEHOST, DISPLAY, etc.).
> GUACAMOLE-422: Add support for timezone redirection

- src/libguac/socket-nest.c
The nested `guac_socket` implementation has apparently been broken for some time. Besides the index not being properly initialized, the data written to the socket is (incorrectly) immediately flushed as a "nest" instruction. This behavior has resulted in the nested socket unit test failing.
These changes correct the above, properly initializing the socket index and properly buffering UTF-8 data for eventual flushing as "nest" instructions.
> GUACAMOLE-662: Correct behavior of nested socket.

- bin/guacctl
- configure.ac
- src/libguac/Makefile.am
As an interface has been changed (a new member has been added to the `guac_user` struct), the libtool version info had to be bumped from 16:0:0 to 17:0:0.
> GUACAMOLE-729: Bump version to 1.1.0.

- src/protocols/kubernetes/kubernetes.c
- src/protocols/kubernetes/settings.c
- src/protocols/kubernetes/settings.h
- src/protocols/kubernetes/user.c
- src/protocols/rdp/rdp.c
- src/protocols/rdp/rdp_cliprdr.c
- src/protocols/rdp/rdp_settings.c
- src/protocols/rdp/rdp_settings.h
- src/protocols/rdp/user.c
- src/protocols/ssh/settings.c
- src/protocols/ssh/settings.h
- src/protocols/ssh/ssh.c
- src/protocols/ssh/user.c
- src/protocols/telnet/settings.c
- src/protocols/telnet/settings.h
- src/protocols/telnet/telnet.c
- src/protocols/telnet/user.c
- src/protocols/vnc/clipboard.c
- src/protocols/vnc/settings.c
- src/protocols/vnc/settings.h
- src/protocols/vnc/user.c
- src/terminal/select.c
- src/terminal/terminal.c
- src/terminal/terminal/terminal.h
This change adds `disable-copy` and `disable-paste` parameters to all protocols, allowing copy/paste to be selectively disabled.
These parameters affect only the transfer of clipboard data through Guacamole. Within the remote desktop or terminal, text can still be copied or pasted independently.
> GUACAMOLE-381: Add parameters for disabling clipboard copy/paste.

- Dockerfile
Quick update to `Dockerfile` to add `ca-certificates` package as a runtime dependency for guacd container.
> GUACAMOLE-694: Add ca-certificates packages as runtime dependency.

- configure.ac
- src/protocols/vnc/client.c
- src/protocols/vnc/vnc.c
- src/protocols/vnc/vnc.h
This pull request implements the `LockWriteToTLS()` and `UnlockWriteToTLS()` callbacks used by LibVNCClient to avoid race conditions when TLS is in use that cause the VNC connection to fail/crash.
Note that support for these callbacks was released in LibVNCServer/Client 0.9.11, so it will only work against 0.9.11 or later- the bug documented in GUACAMOLE-414 will still be present when using libvncserver/client prior to 0.9.11.
> GUACAMOLE-414: Implement TLS Write Locking Callbacks

- Dockerfile
Debian:stable-slim base reduce the final Docker image size.
> GUACAMOLE-772: Reducing Docker image size for Guacd

- src/common-ssh/common-ssh/ssh.h
- src/common-ssh/ssh.c
- src/protocols/rdp/rdp.c
- src/protocols/ssh/ssh.c
- src/protocols/vnc/vnc.c
I'm not 100% certain that this is all that's needed, because I don't have a SSH server to test this against, but, according to the libssh2 documentation, this may be all that's required to allow the session to continue when there's no authentication required.
https://libssh2.org/libssh2_userauth_list.html
> GUACAMOLE-547: Add support for SSH NONE authentication method

- src/protocols/ssh/ssh.c
The password set for a SSH connection is always ignored.
Every SSH password set as connection parameter is now ignored, even if it is not NULL.
The issue is quite simple to reproduce:
1. Set up a working SSH connection with a password parameter with the latest stable (1.0.0).
2. Try the same connection compiling master with GUACAMOLE-547 commits. The terminal prompt the password request, ignoring the configured one.
> GUACAMOLE-547: Do not ignore password from settings.

- src/protocols/rdp/guac_rdpsnd/rdpsnd_service.c
This fixes a memory leak that leaks 4+ GBs over an 8 hour period when continuous audio is being played through RDP.
> GUACAMOLE-847: Fix severe memory leak when using audio with RDP

- src/libguac/user-handlers.c
- src/libguac/user-handlers.h
This adds an empty handler for the nop instruction with a TRACE-level log for received instructions.  I went ahead and left the other logging as DEBUG-level to capture any instructions that should not actually make it through.
> GUACAMOLE-422: Add empty handler and trace logging for nop instruction.

- src/libguac/Makefile.am
- src/libguac/client.c
- src/libguac/encode-jpeg.c
- src/libguac/encode-png.c
- src/libguac/encode-webp.c
- src/libguac/guacamole/client.h
- src/libguac/guacamole/protocol-constants.h
- src/libguac/guacamole/protocol.h
- src/libguac/guacamole/user.h
- src/libguac/protocol.c
- src/libguac/raw_encoder.c
- src/libguac/user.c
This change adds a new function, `guac_protocol_send_argv()`, allowing server-side code to stream argument values to the client. Convenience functions have also been added to make this easier:
* `guac_protocol_send_blobs()` - Automatically splits provided data into a series of `blob` instructions which will not exceed the maximum instruction length.
* `guac_client_stream_argv()` and `guac_user_stream_argv()` - Immediately send the given data as an `argv` stream and subsequent `blob` and `end` instructions, without handling `ack`.
To satisfy the requirements of `guac_protocol_send_blobs()`, I've also added a new constant, `GUAC_PROTOCOL_BLOB_MAX_LENGTH`, which represents a safe maximum blob size, and refactored existing code accordingly. Part of that refactor involved the creation of …
> GUACAMOLE-629: Allow "argv" instructions to be sent from server to client.

- src/protocols/kubernetes/argv.c
- src/protocols/kubernetes/argv.h
- src/protocols/kubernetes/kubernetes.c
- src/protocols/kubernetes/user.c
- src/protocols/ssh/argv.c
- src/protocols/ssh/argv.h
- src/protocols/ssh/ssh.c
- src/protocols/ssh/user.c
- src/protocols/telnet/argv.c
- src/protocols/telnet/argv.h
- src/protocols/telnet/telnet.c
- src/protocols/telnet/user.c
- src/terminal/color-scheme.c
- src/terminal/terminal.c
- src/terminal/terminal/color-scheme.h
- src/terminal/terminal/terminal.h
This change modifies the SSH, telnet, and Kubernetes support to automatically send `argv` streams containing the current values of `font-name`, `font-size`, and `color-scheme`. The current values are sent whenever the relevant parameters are changed or whenever a user joins the connection.
> GUACAMOLE-630: Expose terminal color/font changes.

- src/protocols/vnc/auth.c
- src/protocols/vnc/auth.h
- src/protocols/vnc/settings.c
- src/protocols/vnc/settings.h
- src/protocols/vnc/vnc.c
This pull request implements the callback and parameters required to support additional authentication mechanisms by VNC servers that don't do just password-based authentication.  Ideally this should implement both username/password support as well as X509 support.  I have tested the username/password support and it appears to work - I don't have a way of testing X509 right now so I'm not 100% certain that it will work; however, since I think most of that is handled internally in libvncserver(client), it's reasonable that it will work.
> GUACAMOLE-514: Implement additional VNC authentication support

- src/protocols/rdp/keymaps/base.keymap
When connected with a Guacamole RDP session, the keysym for Caps Lock (0xffe5) is sent over RDP as scancode 0xe03a. Windows does not understand this scancode, thus does not generate the correct VK (Virtual Key) events. Removing +ext from the keymap sends the scancode 0x003a, which is correctly recognized by Windows as Caps Lock. This enables Windows applications to listen for key down and key up events on the Caps Lock key while connected via a Guacamole RDP session.
Note: this issue likely went un-noticed for a long time because it only impacts the key up and down events for the Caps Lock key, not Caps Lock's effect on sending uppercase [A-Z] characters.
Pulling up this [JSBin](https://jsbin.com/reviciceke/2/edit?js,console,output) in the remote desktop is an easy way to see the key …
> GUACAMOLE-859: Incorrect Caps Lock keysym sent to Windows via RDP

- src/protocols/rdp/rdp_fs.h
There is a mistake in the conversion from UNIX time to FILETIME. See the following page: https://support.microsoft.com/en-us/help/167296/how-to-convert-a-unix-time-t-to-a-win32-filetime-or-systemtime. With the current calculation, checking the properties of a file in a redirected drive/folder gives invalid file dates. Changing the '-' to '+' fixes the issue.
> GUACAMOLE-861: Drive redirectrion - fix WINDOWS_TIME calculation

- src/terminal/terminal.c
- src/terminal/terminal/terminal.h
- src/terminal/terminal_handlers.c
As requested on JIRA, here is the patch as a pull request. Please not that I did not test this as I dont know how to put all the pieces in place to check that. It can be easily tested with:
```
printf '\e[?25l' # cursor should be hidden after this
printf '\e[?25h' # cursor should be visible again after this
```
> GUACAMOLE-871: Add support for hidden cursor (DECTECM)

- src/protocols/rdp/rdp.c
The merge of `staging/1.1.0` to `master` resulted in the addition of a warning if both copy and paste are disabled. I think this probably shouldn't be present. An administrator can be expected to intentionally disable both copy and paste in some environments, and warnings should be used only for conditions that the admin should look into and correct when possible.
> GUACAMOLE-249: Remove extra warning resulting from merge.

- configure.ac
- src/protocols/rdp/Makefile.am
This change leverages pkg-config to determine the actual, correct location used by FreeRDP for its plugins, logging the discovered directory in the summary at the end of `configure` and using that directory for the install location of the FreeRDP plugins (regardless of any prefix, libdir, etc. that might otherwise have been given as options to the `configure` script):
```
[mjumper@dev-mjumper guacamole-server]$ ./configure
...
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
------------------------------------------------
guacamole-server version 1.1.0
------------------------------------------------
Library status:
freerdp2 ............ yes
pango ............... yes
libavcodec .......... yes
libavutil ........... yes …
```
> GUACAMOLE-249: Automatically determine correct location for FreeRDP plugins.

- src/protocols/rdp/client.c
- src/protocols/rdp/rdp.c
The `freerdp_settings_new()` function, part of the FreeRDP initialization process, assumes that the `HOME` environment variable will be set and aborts initialization if it isn't, ultimately resulting in a segfault on the Guacamole side.
This change automatically sets the `HOME` variable based on the home directory retrieved from the system's user database. In case initialization still unexpectedly fails, checking has also been added around `freerdp_context_new()` which will abort the connection cleanly rather than segfault.
> GUACAMOLE-927: Automatically set $HOME for sake of FreeRDP initialization process

- src/guacd-docker/bin/build-guacd.sh
The change introduced by #245 actually causes issues with the Docker image build due to the way a separate builder image is used. The image build process expects that absolutely all build artifacts will be installed beneath `/usr/local/guacamole`, but this is no longer the case by default due to the automatic detection of FreeRDP plugin location.
This change overrides the FreeRDP plugin location detection that is part of the guacamole-server build, keeping things together for the sake of the Docker image build and relying instead on the rest of the build to add any symbolic links needed for FreeRDP to find the plugins.
> GUACAMOLE-928: Keep all build artifacts of Docker image within /usr/local/guacamole, including FreeRDP plugins.

- src/libguac/audio.c
- src/libguac/guacamole/audio.h
- src/libguac/guacamole/client.h
- src/libguac/guacamole/user.h
- src/protocols/rdp/Makefile.am
- src/protocols/rdp/beep.c
- src/protocols/rdp/beep.h
- src/protocols/rdp/rdp.c
This change adds support for the [Play Sound PDU](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/e9fb1ecb-191c-45ca-84a0-b7db6366e467), which requests that the client beep at a given frequency and for a given duration.
As written, this support limits the maximum duration of each requested beep to half a second, despite RDP technically supporting beeps up to 50 days long.
> GUACAMOLE-934: Add support for the Play Sound PDU.

- configure.ac
- src/protocols/rdp/bitmap.c
This change adds an test to the `configure` script which determines whether we are building against FreeRDP 2.0.0-rc0, which had a `Bitmap_Free()` which freed bitmaps. For all newer versions of FreeRDP 2.0.0, `Bitmap_Free()` doesn't - it simply wraps the implementation-specific free handler, and it's on the implementation to know which internal parts of `rdpBitmap` were allocated by `Bitmap_Alloc()` and must now be freed.
The latter was handled in commit 8dda26a when the resulting memory leak was discovered during valgrind testing, but this now must be made conditional as this would result in a double-free against 2.0.0-rc0.
Unfortunately, the test itself is awkward:
* It is not possible to test `Bitmap_Free()` behavior in itself. We must test version numbers.
* While we can test numeric …
> GUACAMOLE-935: Free internals of rdpBitmap only when required.

- src/protocols/rdp/plugins/guac-common-svc/guac-common-svc.c
FreeRDP version 2.0.0-rc0 and older will automatically free whatever `entry_points->pInterface` is set to when the channel plugin is unloaded. This doesn't happen in later versions, but will result in a double-free upon disconnect for 2.0.0-rc0 in our case. As we don't need `pInterface`, we can safely set this to `NULL` and avoid the issue entirely.
> GUACAMOLE-935: Do not assign SVC plugin context as it may be automatically freed.

- src/protocols/rdp/Makefile.am
Fixes issue introduced by #253 with trailing whitespace in one of the lines; also fixes style in the Makefile.am file.
> GUACAMOLE-625: Remove trailing whitespace in Makefile.am and fix style

- src/guacd/proc.c
Fix for GUACAMOLE-958.
Two separate problems:
1. Race condition may lead to unwarranted wait and then timeout:
`guacd_timed_client_free()` raced with `guacd_client_free_thread()` for signalling on `free_operation.completed_cond`
2. Potential deadlock/hang of the thread `client_free_thread` if `pthread_cond_timedwait()` failed early or `guacd_client_free_thread()` took longer to reach it's signalling part than the timeout. The reason is that `pthread_cond_timedwait()` re-acquires the mutex before returning 0 or ETIMEDOUT and doesn't ever release it on other errors. Please refer to the man page.
Reference:
http://man7.org/linux/man-pages/man3/pthread_cond_timedwait.3p.html
> GUACAMOLE-958: Avoid race/deadlock in guacd_timed_client_free()

- configure.ac
- src/protocols/rdp/gdi.c
- src/protocols/rdp/gdi.h
- src/protocols/rdp/rdp.c
- src/protocols/rdp/settings.c
This change requests relaxed validation of server orders if supported by FreeRDP, warning the user during the build process if their version of FreeRDP lacks this support.
Fallback support for OpaqueRect and PatBlt orders is restored through reverting commit 9855d875c794e9517567e89ad13acccd7e7e03d0, allowing RDP servers that (incorrectly) assume support for those orders to generally function without introducing visual artifacts.
> GUACAMOLE-962: Allow misbehaving RDP servers to use OpaqueRect and PatBlt.

- bin/guacctl
- configure.ac
This pull request bumps the server versions to 1.2.0.  I did not modify the libguac version, as that has not changed (yet).
> GUACAMOLE-966: Bump server version to 1.2.0

- src/protocols/rdp/settings.c
FreeRDP 2.0.0 will automatically free all settings strings when the settings structure is freed. As we will also do the same for our own settings strings, the FreeRDP settings must be kept independent. This change adds calls to `guac_rdp_strdup()` for the few strings remaining that lacked this call.
Note that we can't simply not free the strings on our side and rely purely on FreeRDP to do so. There is no guarantee that FreeRDP will be given control of the strings before before an error causes the Guacamole connection to abort, nor is there any guarantee that the FreeRDP settings structure will not need to be repeatedly recreated from the same source material (the original copies of those strings) during an automatic internal reconnect.
> GUACAMOLE-979: Ensure all FreeRDP settings strings are independent duplicates of their corresponding Guacamole settings.

- src/protocols/rdp/user.c
I have fixed the GUACAMOLE-982 issue.
> GUACAMOLE-982: Fix the error log message when the creating thread of RDP client fails

- src/protocols/rdp/channels/rdpdr/rdpdr-fs-messages-file-info.c
- src/protocols/rdp/channels/rdpdr/rdpdr-fs-messages.c
- src/protocols/rdp/channels/rdpdr/rdpdr-messages.c
- src/protocols/rdp/channels/rdpdr/rdpdr-printer.c
- src/protocols/rdp/channels/rdpdr/rdpdr.c
- src/protocols/rdp/channels/rdpsnd/rdpsnd-messages.c
- src/protocols/rdp/channels/rdpsnd/rdpsnd.c
- src/protocols/rdp/plugins/guac-common-svc/guac-common-svc.c
- src/protocols/rdp/plugins/guacai/guacai-messages.c
- src/protocols/rdp/plugins/guacai/guacai.c
This implements the use of the `Stream_GetRemainingLength()` function prior to reading RDP Streams throughout the code.
There is one place that I need a little help with - will make a note at the correct place in the pull request...
> GUACAMOLE-1059: Use FreeRDP function for verifying Stream length

- src/protocols/rdp/channels/rdpsnd/rdpsnd-messages.c
The index of the RDPSND format should be checked against the maximum number of formats supported (`GUAC_RDP_MAX_FORMATS`), not the byte size of the underlying array (`sizeof(rdpsnd->formats)`).
> GUACAMOLE-1059: Correct verification of sound format index.

- src/common-ssh/common-ssh/sftp.h
- src/common-ssh/sftp.c
- src/protocols/rdp/channels/rdpdr/rdpdr-fs-messages.c
- src/protocols/rdp/fs.c
- src/protocols/rdp/fs.h
- src/protocols/rdp/rdp.c
- src/protocols/rdp/settings.c
- src/protocols/rdp/settings.h
- src/protocols/rdp/user.c
- src/protocols/ssh/settings.c
- src/protocols/ssh/settings.h
- src/protocols/ssh/ssh.c
- src/protocols/ssh/user.c
- src/protocols/vnc/settings.c
- src/protocols/vnc/settings.h
- src/protocols/vnc/user.c
- src/protocols/vnc/vnc.c
This change adds options for the protocols that support various file transfer mechanisms to disable either uploads or downloads (or both) if so desired.
I took the approach of creating new boolean options for this, which seems the simplest approach; however, I did think of one possible alternative approach which would be to change the current "Enable Drive" (RDP) and "Enable SFTP" (RDP, SSH, and VNC) options such that, instead of boolean (checkbox), they are multi-option (select) with enable, upload-only, download-only, or disabled.  Let me know if that seems a better approach.
> GUACAMOLE-474: Allow file uploads and downloads to be disabled

- src/protocols/rdp/channels/rdpdr/rdpdr-fs-messages.c
Fixes two issues with the recently-committed changes.
> GUACAMOLE-474: Correct variable name and scope errors in RDP fs code.

- src/protocols/rdp/settings.h
I have fixed the GUACAMOLE-1103 issue.
> GUACAMOLE-1103: Fix the incorrect comment of the enable_sftp variable of the guac_rdp_settings structure.

- src/common/common/defaults.h
- src/libguac/wol.c
- src/protocols/rdp/settings.c
- src/protocols/ssh/settings.c
- src/protocols/telnet/settings.c
- src/protocols/vnc/settings.c
In addition to the issues identified by Coverity for socket open failures, this pull request enhances error logging and also changes the default boot time to zero in the recently-merged Wake-on-LAN functionality.
> GUACAMOLE-513: Several updates to Wake-on-LAN functionality

- src/protocols/rdp/client.c
- src/protocols/rdp/input.c
- src/protocols/rdp/rdp.c
- src/protocols/rdp/rdp.h
Added a read/write lock to the **guac_rdp_client** structure, and acquire/release the lock in input handlers and RDP client thread.
I was not able to reproduce a segmentation fault with this patch applied.
> GUACAMOLE-1053: guacd segfaults if user actively presses keys during RDP disconnect

- src/protocols/rdp/channels/rail.c
The handshake procedure implemented by Apache Guacamole 1.1.0 for RemoteApp is partially incorrect, omitting the Client Information PDU. Without this PDU, RemoteApp behaves unexpectedly, launching multiple copies of the requested application.
In investigating this, additional differences from the 1.0.0 release were identified and have also been addressed here:
* The `RAIL_EXEC_FLAG_EXPAND_ARGUMENTS` flag was missing from the Client Execute PDU.
* Several system parameters were not specified, having previously been included by default via FreeRDP's internal implementation of RAIL. These are now explicitly specified.
* System Parameters Update PDUs were not being sent at all because the `params` flags were unset. These flags are used within FreeRDP to denote which system parameters are …
> GUACAMOLE-1076: Correct RemoteApp launch behavior.

- src/libguac/Makefile.am
Interfaces have been added to libguac for this release (support for WoL), but no existing interface has been changed or removed.
The guidelines we must follow for updating the version info are here: https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html
> GUACAMOLE-966: Bump libguac version number for 1.2.0.

- configure.ac
- src/guacenc/Makefile.am
- src/guacenc/ffmpeg-compat.c
- src/guacenc/ffmpeg-compat.h
- src/guacenc/guacenc.c
- src/guacenc/man/guacenc.1.in
- src/guacenc/video.c
- src/guacenc/video.h
This change builds off #159, adding the following additional changes:
* Minor corrections to address the comment style nitpicks from the latest review of #159.
* Minor update to the guacenc manpage, noting that the output is now simply normal MPEG-4 video (now a raw MPEG-4 video stream).
The original commits from #159 are here and untouched.
> GUACAMOLE-465: Produce MPEG-4 output within a proper container.

- src/guacenc/video.c
In the event that `failed_header` is `true`, the `guacenc_video` structure is still allocated prior to aborting, resulting in a minor leak.
As there is no need to proceed with allocation of `guacenc_video` after the failure which results in this flag being set, and the additional error logged later due to that flag appears to duplicate the purpose of the error originally logged, simply merging that handling removes the possibility of a leak.
> GUACAMOLE-465: Correct possible leak of malloc'd video structure.

- src/guacenc/video.c
There are a couple issues with `access()` and `remove()` as they are currently used within guacenc:
* If checking `access()` prior to attempting `remove()` in order to avoid a failed removal, there is no guarantee that the status of the file pending removal will not change between the calls. This sort of check should be made atomically.
A good way to do this is through just attempting the removal and handling the possible failure. If the file does not exist, that is one of the distinct types of failures that will be reported.
* `remove()` is useful when the type of file is unknown, as it will automatically choose between `unlink()` and `rmdir()` depending on whether the file is a directory. As we know ahead of time that this file will never be a directory, it is more appropriate to use …
> GUACAMOLE-465: Remove superfluous access check prior to attempting file deletion.

- src/guacenc/video.c
A few usages of `guacenc_log()` within guacenc are incorrect:
* The newline character is automatically added. Specifying it manually as part of the string will result in two newline characters being present.
* The `%d` format specifier was given for a string parameter, when `%s` was likely intended ("s" is right next to "d").
These changes remove the extra `\n` and switch the incorrect usage of `%d` to `%s`.
> GUACAMOLE-465: Correct usage of printf-like guacenc_log().

- src/common-ssh/sftp.c
- src/protocols/rdp/channels/rdpdr/rdpdr-fs-messages-file-info.c
- src/protocols/rdp/download.c
- src/protocols/rdp/upload.c
This change:
* Corrects a bug in the new download restrictions which failed to block:
1. Downloads initiated using the RDPDR `Download` folder
2. Downloads initiated via the Guacamole menu (using `get` instructions)
* Adds additional low-level blocking, in case an unknown bug should surface which attempts to initiate a download or service an upload, despite the same being disabled.
> GUACAMOLE-474: Properly enforce file new upload/download restrictions.

- Dockerfile
Dockage image size will reduced by install only package dependencies (without recommendations). The guacd process runs as a non-privileged user and will be checked by netcat.
> GUACAMOLE-1110: Size and security improvements for Docker images

- src/libguac/Makefile.am
- src/libguac/argv.c
- src/libguac/guacamole/argv-constants.h
- src/libguac/guacamole/argv-fntypes.h
- src/libguac/guacamole/argv.h
- src/protocols/kubernetes/argv.c
- src/protocols/kubernetes/argv.h
- src/protocols/kubernetes/client.c
- src/protocols/kubernetes/settings.c
- src/protocols/kubernetes/user.c
- src/protocols/ssh/argv.c
- src/protocols/ssh/argv.h
- src/protocols/ssh/client.c
- src/protocols/ssh/settings.c
- src/protocols/ssh/user.c
- src/protocols/telnet/argv.c
- src/protocols/telnet/argv.h
- src/protocols/telnet/client.c
- src/protocols/telnet/settings.c
- src/protocols/telnet/user.c
This change adds a new header to libguac, `argv.h`, which provides a series of convenience functions for automatically handling "argv" streams:
* `guac_argv_register()` - Registers a callback which should be invoked when the full, updated value of an argument has been received via an "argv" stream. Option flags can be specified to declare that a particular callback should be invoked only once, or that received values should be echoed back to all users of the connection.
* `guac_argv_received()` - Hands over control of a received "argv" stream such that registered callbacks will automatically be invoked.
* `guac_argv_handler` - Convenient implementation of the "argv" instruction handler which automatically handles sending of "ack" instructions and invokes `guac_argv_received()` …
> GUACAMOLE-221: Add convenience API for automatically handling received "argv" streams.

- src/protocols/rdp/channels/audio-input/audio-input.c
I have just fixed one typo mistake in the following path:
**src/protocols/rdp/channels/audio-input/audio-input.c**
> GUACAMOLE-1185: Fixed one typo mistake.

- configure.ac
- src/protocols/rdp/channels/common-svc.c
- src/protocols/rdp/plugins/guac-common-svc/guac-common-svc.c
This change automatically frees a sent `wStream` after the corresponding write has been completed or cancelled. As FreeRDP will automatically free this `wStream` for us from 2.0.0-rc3 through 2.0.0-rc4 (and manually doing so would result in a double-free), this behavior is controlled by a macro and compile-time checks.
Since the internal behavior of FreeRDP generally cannot be detected outside version number checks, and version number checks are only a reliable indication of behavior for actual releases and RCs, I have also added a warning that will be displayed at build time if a development version of FreeRDP is being used:
```
checking whether FreeRDP appears to be a development version... yes
configure: WARNING:
--------------------------------------------
You are building against a …
```
> GUACAMOLE-1181: Rely on automatic freeing of wStream only for FreeRDP 2.0.0-rc3 through 2.0.0-rc4.

- src/guacd/proc.c
The call to `guac_socket_require_keep_alive()` is currently in the wrong spot, being invoked just after the connection has ended. This results in the user seeing a server timeout error if they fail to enter their credentials quickly. It should instead be invoked at the start of the connection.
> GUACAMOLE-221: Ensure guacd always enables broadcast socket keep-alive.

- src/libguac/socket.c
The keep-alive interval is identical to the timed client free used by guacd. This results in a race condition where there is a random chance that guacd will assume that the client has failed to terminate in a timely manner simply because `guac_socket_free()` is waiting for the keep-alive thread to finish, resulting in log noise and a forced kill of the connection process.
This change forces the sleeping keep-alive thread to cease running with `pthread_cancel()`. The keep-alive thread itself uses `pthread_setcancelstate()` to ensure that the only cancellation point within the thread is the call to `nanosleep()`.
> GUACAMOLE-221: Terminate keep-alive thread immediately upon guac_socket_free().

- src/protocols/rdp/error.c
- src/protocols/rdp/error.h
- src/protocols/rdp/rdp.c
Currently, if the user enters incorrect credentials when prompted, they are advised that the remote desktop server is unavailable. This is incorrect and results from the RDP support not handling the error code(s) associated within invalid login attempts, which may not be exposed within the disconnect reason.
These changes handle the additional error codes supported by FreeRDP that expose whether the connection has failed due to incorrect credentials.
> GUACAMOLE-221: Rely on FreeRDP error code if no RDP disconnect reason is available.

- src/protocols/rdp/error.c
The changes from #308 broke the build against FreeRDP 2.0.0-rc2 and earlier. This is because earlier versions of FreeRDP do not support all the constants used within `error.c`.
This change wraps affected constants in `#ifdef` / `#endif`, handling that specific error constant only if it's actually defined.
> GUACAMOLE-221: Handle FREERDP_ERROR_* constants only when defined.

- bin/guacctl
- configure.ac
- src/libguac/Makefile.am
Updates `guacamole-server` versions for `1.3.0` version release, including `libguac` due to changes from GUACAMOLE-221. I think I did the update to `libguac` correctly, but I'm a little uncertain on the `age` field for this release, so let me know if that needs to be tweaked.
> GUACAMOLE-1205: Update Guacamole Server version numbers for 1.3.0 release

- configure.ac
- src/protocols/vnc/auth.c
- src/protocols/vnc/auth.h
- src/protocols/vnc/vnc.c
This change alters the VNC build such that support for additional authentication mechanisms is built only if libvncclient supports those mechanisms. If the necessary support is not present, only password authentication will be usable.
> GUACAMOLE-1227: Build support for generic VNC credentials only if supported by libvncclient.

- Dockerfile
Hi,
This PR is a slight modification to #292 which has been merged in `staging/1.3.0` (thus my PR against this branch).
It creates a dedicated group for the `guacd` service user.
So that it is not assigned to the default `users` group, among other possible users...
Thank you 👍
> GUACAMOLE-1110: Create a proper dedicated service group

- src/libguac/tests/parser/read.c
- src/libguac/tests/socket/fd_send_instruction.c
- src/libguac/tests/socket/nested_send_instruction.c
There is a small typo in src/libguac/tests/parser/read.c, src/libguac/tests/socket/fd_send_instruction.c, src/libguac/tests/socket/nested_send_instruction.c.
Should read `verifying` rather than `verfying`.
Fixes https://issues.apache.org/jira/browse/GUACAMOLE-1225
> GUACAMOLE-1225: fix simple typo, verfying -> verifying, in code documentation

- src/guacd/log.c
- src/libguac/user-handshake.c
It is expected under normal circumstances that the connection may be abruptly closed, including during the handshake. For example, this will commonly occur when a TCP load balancer is performing a simple service health check.
An message noting that the connection has been closed during the Guacamole protocol handshake is really only of benefit when debugging, where that information may provide useful context. If not debugging, the message amounts to log noise.
> GUACAMOLE-1242: Move "connection closed" log message to debug level.

- Dockerfile
- configure.ac
Currently, the Docker image for guacd built from the `staging/1.3.0` branch produces the following double-free error:
```
...
guacd[24698]: INFO:	Loading keymap "base"
guacd[24698]: INFO:	Loading keymap "en-us-qwerty"
guacd[24698]: INFO:	Connected to RDPDR 1.13 as client 0x0005
free(): double free detected in tcache 2
guacd[6]: INFO:	Connection "$e6955582-c6f2-4912-a4bd-a3ffee002cd1" removed.
```
This is because the Docker image is built from Debian stable, and the version of FreeRDP currently packaged by Debian stable is not a FreeRDP release but rather a development snapshot ([commit 2693389](https://github.com/FreeRDP/FreeRDP/commit/2693389a103394e035edc2a01055ca2c9ccccb21)) from after 2.0.0-rc4 but before 2.0.0. In that span of time, the handling of memory within FreeRDP changed, and …
> GUACAMOLE-1241: Avoid double-free when building against FreeRDP development snapshot.

- configure.ac
- src/libguac/id.c
- src/libguac/tests/Makefile.am
- src/libguac/tests/id/generate.c
This change adds support for libuuid (part of util-linux) as a means of ID generation, leveraging that library in favor of OSSP UUID. If libuuid is unavailable, OSSP UUID will be used.
A unit test has also been added to verify that ID generation works as expected.
> GUACAMOLE-1254: Add support for libuuid as alternative to OSSP UUID.

- src/protocols/rdp/plugins/guac-common-svc/guac-common-svc.c
The changes introduced by GUACAMOLE-1181 (commit 2c86e20) were made conditional as older versions of FreeRDP will automatically free the `wStream`, resulting in a double-free if we attempt to do so ourselves.
The macro controlling that conditional code is defined within `config.h`, which is missing here. Without that macro, the call to `Stream_Free()` always occurs, and we get a double-free with older FreeRDP.
> GUACAMOLE-1259: Include missing config.h header for sake of conditional Stream_Free().

- src/protocols/vnc/client.c
Older versions of libvncclient did not free all memory within `rfbClientCleanup()`, but this has been corrected as of their 0.9.12
release. As guacamole-server may well be built against older versions of libvncclient, we can't simply remove the manual `free()` calls, but we should be sure to set any memory that we free ourselves to `NULL` so that `rfbClientCleanup()` does not attempt to free it again.
> GUACAMOLE-1263: Mark freed memory as freed prior to calling rfbClientCleanup().

- src/common-ssh/ssh.c
- src/protocols/vnc/vnc.c
This small change does some initialization on the GCrypt library used by libvncclient prior to the VNC client start-up. In my testing this looks to resolve the GUACAMOLE-1133 issue, which deals with failures to connect to Apple Remote Desktop systems. Further testing would be greatly appreciated. I'm also not 100% sure what options we should be using to initialize GCrypt - this is a very basic initialization of the library and then some secure memory.
> GUACAMOLE-1133: initialize GCrypt in VNC protocol prior to client start-up

- Dockerfile
- configure.ac
Copied the check from libssh2 for gcrypt support and adapted it for libvncserver. Should fix the current build issues, and I also added Dockerfile update to include `libgcrypt-dev` in the build requirements.
> GUACAMOLE-1133: Add build check for headers when libvncserver includes gcrypt support

- src/protocols/rdp/keymaps/fr_be_azerty.keymap
When using the fr-be-azerty remote keyboard layout on an RDP connection, the dash ('-') and underscore ('_') are swapped.
Underscore and dash are located on the same key on a Belgian azerty layout. Dash should be the normal/unshifted character, and underscore should be the shifted character. The current mapping has this the other way around, so let's fix this.
Jira issue: https://issues.apache.org/jira/browse/GUACAMOLE-1277
> GUACAMOLE-1277: Unswap -/_ on fr-be-azerty keymap

- src/common/common/recording.h
- src/common/common/surface.h
- src/common/recording.c
- src/common/surface.c
- src/libguac/guacamole/protocol-constants.h
- src/libguac/guacamole/protocol.h
- src/libguac/guacamole/user-fntypes.h
- src/libguac/guacamole/user.h
- src/libguac/protocol.c
- src/libguac/user-handlers.c
- src/libguac/user-handlers.h
- src/protocols/kubernetes/kubernetes.c
- src/protocols/rdp/Makefile.am
- src/protocols/rdp/channels/rdpei.c
- src/protocols/rdp/channels/rdpei.h
- src/protocols/rdp/client.c
- src/protocols/rdp/input.c
- src/protocols/rdp/input.h
- src/protocols/rdp/rdp.c
- src/protocols/rdp/rdp.h
- src/protocols/rdp/settings.c
- src/protocols/rdp/settings.h
- src/protocols/rdp/user.c
- src/protocols/ssh/ssh.c
- src/protocols/telnet/telnet.c
- src/protocols/vnc/vnc.c
This change adds RDP support for processing of received multi-touch events leveraging the RDPEI channel. If enabled on the connection and supported by the RDP server, this allows direct touch interaction with applications running within the remote desktop that support touch.
This new support relies on:
* A new Guacamole instruction, `touch`, which communicates the details of each touch contact from client to server.
* A new Guacamole layer parameter, `multi-touch`, which allows the server to report to the client that touch events are supported (to allow the client to decide whether to rely on mouse emulation vs. touch pass-through).
Each touch event consists of:
* An arbitrary ID (to distinguish one contact from another)
* X/Y coordinates
* An approximation of the contact area (X/Y radius …
> GUACAMOLE-1204: Add server-side support for pass-through of multi-touch events.

- src/protocols/kubernetes/kubernetes.c
- src/protocols/kubernetes/settings.c
- src/protocols/kubernetes/settings.h
- src/protocols/kubernetes/url.c
- src/protocols/kubernetes/url.h
Added support for using `exec` for attaching to kubernetes pods.
Modified generation of Kubernetes API endpoint.
Added connection argument  _exec-command_.
**exec_command:**
The command used by exec call. If omitted, attach call will be used.
Used to run a new process and attach to it, instead of the main container process.
> GUACAMOLE-1174: Added exec call implementation for kubernetes protocol

- configure.ac
- src/protocols/kubernetes/.gitignore
- src/protocols/kubernetes/tests/Makefile.am
- src/protocols/kubernetes/tests/url/append.c
- src/protocols/kubernetes/tests/url/escape.c
- src/protocols/kubernetes/url.c
- src/protocols/kubernetes/url.h
The implementation of `guac_kubernetes_append_endpoint_param()` added via #301 does not correctly handle detection of truncation when appending a parameter to a URL. The previous implementation passed `length - str_len` to `snprintf()`, yet compared the return value to `length`. This is incorrect, as `length` is not the buffer size provided to `snprintf()`.
This change:
* Corrects the logic within `guac_kubernetes_append_endpoint_param()` such that truncation is correctly detected.
* Adds unit tests for the URL utility functions to verify correct behavior.
* Clarifies the documented behavior of `guac_kubernetes_append_endpoint_param()` a bit further.
The new unit tests fail without the correction to the `guac_kubernetes_append_endpoint_param()` logic, which has been kept in a separate …
> GUACAMOLE-1174: Correct handling of truncated parameters when appending to URLs.

- src/common/common/display.h
- src/common/common/surface.h
- src/common/display.c
- src/common/surface.c
- src/protocols/rdp/rdp.c
- src/protocols/rdp/settings.c
- src/protocols/rdp/settings.h
- src/protocols/vnc/settings.c
- src/protocols/vnc/settings.h
- src/protocols/vnc/vnc.c
- src/terminal/display.c
This change adds a new `force-lossless` parameter to the VNC and RDP support, allowing the default lossy compression heuristics to be overridden. The default "use lossy compression if it looks appropriate" behavior of connections remains the same unless overridden with this new parameter.
> GUACAMOLE-1302: Add support for forcing lossless compression on VNC/RDP connections.

- src/protocols/rdp/channels/audio-input/audio-buffer.c
- src/protocols/rdp/channels/audio-input/audio-buffer.h
- src/protocols/rdp/channels/cliprdr.c
- src/protocols/rdp/channels/common-svc.c
- src/protocols/rdp/channels/disp.c
- src/protocols/rdp/channels/disp.h
- src/protocols/rdp/channels/rail.c
- src/protocols/rdp/channels/rdpei.c
- src/protocols/rdp/channels/rdpei.h
- src/protocols/rdp/client.c
- src/protocols/rdp/input.c
- src/protocols/rdp/keyboard.c
- src/protocols/rdp/plugins/guacai/guacai-messages.c
- src/protocols/rdp/rdp.c
- src/protocols/rdp/rdp.h
The FreeRDP library is intended to be threadsafe, but is not reliably so with respect to legacy RDP encryption and outbound messages. When outbound messages are sent by multiple threads, the encryption key used for legacy RDP encryption may not be updated correctly, resulting in a fatal connection error like:
> "ERRINFO_DECRYPT_FAILED (0x00001192):(a) Decryption using Standard RDP Security mechanisms (section 5.3.6) failed. (b) Session key creation using Standard RDP Security mechanisms (section 5.3.5) failed."
These changes add synchronization around absolutely all parts of the RDP support that may send RDP messages, including `freerdp_check_event_handles()`.
> GUACAMOLE-1283: Add synchronization around absolutely all outbound RDP messages.

- src/protocols/rdp/channels/audio-input/audio-buffer.c
- src/protocols/rdp/channels/audio-input/audio-buffer.h
These changes are a fresh attempt at addressing the issue with audio input packet timing originally identified by @myjimmy. They take a similar approach to his proposed changes (#312), and are intended to achieve the same fix in principle (throttling audio data) while addressing the issues noted in code review of the original PR. Specifically:
* Packet scheduling should be dynamic and based on the needs of the RDP server.
* The flush thread should not poll the audio buffer in a loop to check for new data, but wait for that data to be received.
* While received audio data does need to be buffered to compensate for difference in packet size and timing, that buffer needs to be finite. It should not grow without bound.
I've tried to describe the nature of these changes in detail in the commit …
> GUACAMOLE-1201: Throttle outbound audio data to avoid overflowing RDP server audio input buffer.

- src/protocols/rdp/upload.h
Fixes the regression introduced by GUACAMOLE-249 where the file upload offset gets set to a 32-bit integer instead of a 64-bit unsigned integer.
> GUACAMOLE-1276: Correct file upload offset type.

- src/common/json.c
Looks like this should resolve the issue with correcting the escape of back-slashes in SFTP code. I just did it at the raw JSON level, as it's a character that should be escaped universally in JSON strings.
Verified that this works by creating a file with a backslash on an SFTP location and verifying that it lists correctly in the hidden menu.
> GUACAMOLE-1215: Add backslash to list of JSON-escaped characters.

- src/protocols/rdp/Makefile.am
- src/protocols/rdp/keymaps/no_no_qwerty.keymap
@jmoehlma Best guess... How do I test this?
> GUACAMOLE-1064: add Norwegian keyboard

- src/protocols/rdp/channels/cliprdr.c
- src/protocols/rdp/channels/disp.c
- src/protocols/rdp/channels/rdpei.c
- src/protocols/rdp/rdp.c
Without these changes, RDP-specific resources like the CLIPRDR and RDPEI channels may remain from past connections if the RDP connection is dynamically reconnected via the "Reconnect" display resize method, resulting in assertion failures or memory errors if those stale resources are reused after reconnect is completed.
> GUACAMOLE-1388: Ensure RDP-specific resources are cleaned up after channel disconnect.

- src/protocols/ssh/ssh.c
GUACAMOLE-1416: Fix unreleased the lock ssh_client->term_channel_lock in the ssh_client_thread.
> GUACAMOLE-1416: Fix unreleased the lock in the ssh_client_thread

- bin/guacctl
- configure.ac
- src/libguac/Makefile.am
The libtool version info also needs a full bump, as at least one interface was modified since 1.3.0 (the new `touch_handler` member of `guac_user`).
> GUACAMOLE-1411: Bump version numbers to 1.4.0.

- src/guacd/connection.c
This change builds off #271, removing the unnecessary/unsafe usage of `snprintf()` and instead using purely `guacd_log()`.
> GUACAMOLE-1047: Notify connecting client of invalid connection IDs.

- src/guacd/conf-file.c
- src/guacd/conf.h
This change explicitly uses the hostname "localhost" as the default guacd bind host, matching the default used by the webapp:
https://github.com/apache/guacamole-client/blob/841b659a20e0b72f3b548ece5bde5556b1dc4ce1/guacamole-ext/src/main/java/org/apache/guacamole/environment/LocalEnvironment.java#L67-L71
This should ensure:
* Both guacd and the webapp have the same default behavior (the old `NULL` behavior for address info lookups is not necessarily the same as a lookup for "localhost").
* The new behavior is compatible with the expectations of deployments of past releases (the webapp has always defaulted to attempting to connect to "localhost").
> GUACAMOLE-1190: Explicitly use "localhost" as guacd default bind host, matching default of webapp.

- src/common/common/iconv.h
- src/common/iconv.c
- src/common/tests/Makefile.am
- src/common/tests/iconv/convert-test-data.c
- src/common/tests/iconv/convert-test-data.h
- src/common/tests/iconv/convert.c
- src/protocols/rdp/channels/cliprdr.c
- src/protocols/rdp/settings.c
- src/protocols/rdp/settings.h
This change adds a new connection parameter for RDP, `normalize-clipboard`, that allows the line endings within clipboard data to be normalized to a particular format, such as Windows (CRLF) or Unix (LF).
By default, no normalization is performed.
> GUACAMOLE-478: Add clipboard line ending normalization option for RDP.

- src/common/recording.c
- src/terminal/typescript.c
To allow reading by separate services like the Guacamole web application, recordings/typescripts created by guacd should be group-readable. Without group read permission, the service user running guacd would also need to be the user running the web application, which would not be an ideal separation of privileges.
> GUACAMOLE-462: Create recordings/typescripts with group read permission.

- src/protocols/rdp/Makefile.am
- src/protocols/rdp/keymaps/pl_pl_qwerty.keymap
This PR adds pl_pl_qwerty.keymap file with Polish keyboard layout for RDP and updates Makefile.am to include aforementioned file. I've tested those changes locally as per contribution guidelines and they work as expected.
> GUACAMOLE-1495: Add keymap for Polish keyboard layout for RDP

- src/protocols/rdp/channels/disp.c
This should fix the following:
```
...
Thread 2.4 "guacd" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe90c9700 (LWP 3015513)]
0x00007ffff6746b72 in guac_rdp_disp_reconnect_needed (disp=0x7ffff0052d80)
at channels/disp.c:284
284	    if (rdp_client->filesystem->open_files > 0)
(gdb) print rdp_client
$1 = (guac_rdp_client *) 0x7ffff0052c40
(gdb) print rdp_client->filesystem
$2 = (guac_rdp_fs *) 0x0
(gdb) 
```
> GUACAMOLE-876: Test for open files only if filesystem has been allocated.

- Dockerfile
- src/guacd-docker/bin/list-dependencies.sh
See [GUACAMOLE-1540](https://issues.apache.org/jira/browse/GUACAMOLE-1540) - this change is confirmed to fix the SSH key extraction issues I was having with the old buster build.
The only real changes of note here are the replacement of `libjpeg62-turbo-dev` with `libjpeg-dev`, and the modification of the `list-dependencies.sh` script to change the way it identifies dependencies.
When testing out this change, I found that the file paths that were linked against are _NOT_ the same paths that are package-managed. 
For example: `libjpeg-turbo8` packages `/usr/lib/x86_64-linux-gnu/libjpeg.so.8`, but the libraries are actually built against `/lib/x86_64-linux-gnu/libjpeg.so.8.2.2`. These two files are hard-linked, but `dpkg` does not understand this, so it failed to find the `libjpeg-turbo8` …
> GUACAMOLE-1540: Docker build using Ubuntu 21.10 as a base

- src/protocols/kubernetes/kubernetes.c
- src/protocols/kubernetes/settings.c
- src/protocols/kubernetes/settings.h
- src/protocols/ssh/settings.c
- src/protocols/ssh/settings.h
- src/protocols/ssh/ssh.c
- src/protocols/telnet/settings.c
- src/protocols/telnet/settings.h
- src/protocols/telnet/telnet.c
- src/terminal/Makefile.am
- src/terminal/terminal.c
- src/terminal/terminal/terminal.h
As described in [GUACAMOLE-1538](https://issues.apache.org/jira/projects/GUACAMOLE/issues/GUACAMOLE-1538), this change modifies the `libguac_terminal` library to be a shared library, instead of being duplicated into each of the three existing terminal-based libaries (ssh, telnet, and kubernetes).
In addition, this change also refactors the way that the `guac_terminal` is created - rather than including every possible parameter into `guac_terminal_create`, there is now an `guac_terminal_options` struct, which only requires that a few required parameters be specified (client, clipboard, width, height, and dpi).
All other parameters can be set directly if needed. This should allow new parameters to be added without having to modify the call to `guac_terminal_create` for every user of this …
> GUACAMOLE-1538: Refactor libguac_terminal for easier extensibility, and migrate to shared library.

- src/common/Makefile.am
- src/libguac/Makefile.am
- src/libguac/guacamole/recording.h
- src/libguac/recording.c
- src/protocols/kubernetes/input.c
- src/protocols/kubernetes/kubernetes.c
- src/protocols/kubernetes/kubernetes.h
- src/protocols/rdp/client.c
- src/protocols/rdp/input.c
- src/protocols/rdp/rdp.c
- src/protocols/rdp/rdp.h
- src/protocols/ssh/client.c
- src/protocols/ssh/input.c
- src/protocols/ssh/ssh.c
- src/protocols/ssh/ssh.h
- src/protocols/telnet/client.c
- src/protocols/telnet/input.c
- src/protocols/telnet/telnet.c
- src/protocols/telnet/telnet.h
- src/protocols/vnc/client.c
- src/protocols/vnc/input.c
- src/protocols/vnc/vnc.c
- src/protocols/vnc/vnc.h
From https://issues.apache.org/jira/browse/GUACAMOLE-1543:
Session recording functionality, such as guac_common_recording, is used within every protocol library that supports session recording.
Everything needed to support session recording should be moved to a public library so that new protocols can be developed to support session recording without having to be build inside the guacamole-server build.
> GUACAMOLE-1543: Move recording functionality from common to libguac.

- src/protocols/rdp/client.c
- src/protocols/rdp/print-job.c
As handling of inbound Guacamole messages for the RDP support is inherently tied to the overall RDP `message_lock` (this lock must be acquired before sending out the RDP versions of received mouse events, keyboard events, etc.), the RDP print process has the potential to deadlock if it needs to wait for an inbound "ack" message. The `message_lock` will be acquired before requesting that FreeRDP handle the RDP event queue (the part of the library that performs housekeeping functions around the print job), which may block handling of Guacamole events like "ack".
(See https://issues.apache.org/jira/browse/GUACAMOLE-1115?focusedCommentId=17508379&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17508379)
This change alters the print job handling to temporarily …
> GUACAMOLE-1115: Ensure RDP print process does not block itself from completing.

- src/libguac/client.c
- src/libguac/guacamole/client.h
- src/libguac/guacamole/protocol.h
- src/libguac/protocol.c
- src/libguac/user-handlers.c
- src/protocols/rdp/Makefile.am
- src/protocols/rdp/channels/cliprdr.c
- src/protocols/rdp/channels/disp.c
- src/protocols/rdp/channels/rail.c
- src/protocols/rdp/channels/rdpei.c
- src/protocols/rdp/channels/rdpgfx.c
- src/protocols/rdp/channels/rdpgfx.h
- src/protocols/rdp/gdi.c
- src/protocols/rdp/gdi.h
- src/protocols/rdp/pointer.c
- src/protocols/rdp/rdp.c
- src/protocols/rdp/rdp.h
- src/protocols/rdp/settings.c
- src/protocols/rdp/settings.h
This change adds initial RemoteFX support for RDP, enabled via the `enable-gfx` parameter. As RemoteFX includes explicit frame boundaries, and thus allows us to actually track when frames are received, when Guacamole needs to combine them, etc., these changes also include enhancements to the Guacamole protocol that allow the client to track performance with respect to framerate and frame dropping.
> GUACAMOLE-377: Add support for RemoteFX.

- src/libguac/tests/socket/fd_send_instruction.c
- src/libguac/tests/socket/nested_send_instruction.c
The new `guac_protocol_send_sync()` requires an additional parameter - the number of logical frames associated with the sync:
https://github.com/apache/guacamole-server/blob/ffb6c809bebff431bb195685d35bb304f86a9910/src/libguac/guacamole/protocol.h#L372-L375
#363 added this parameter but did make corresponding updates to the unit tests, thus breaking the build on Jenkins. These changes update the unit tests to include the new parameter.
> GUACAMOLE-377: Update unit tests for new prototype of guac_protocol_send_sync().

- src/common-ssh/ssh.c
- src/guacd/daemon.c
This change fixes the issues with SFTP + VNC as described here: https://issues.apache.org/jira/browse/GUACAMOLE-1652.
> GUACAMOLE-1652: Only call SSL init functions when the library version requires it.

- src/guacd-docker/bin/list-dependencies.sh
As noted by @myamoto on #388, the new Alpine-based Docker build does not correctly determine the packages needed to satisfy runtime dependencies. This is because the `list-dependencies.sh` script was erroring out early when it ran into a library that our new Docker build manually builds itself, causing the dependencies of other files to be ignored.
This changes corrects the above by:
* Ignoring if `apk` cannot determine the package for a particular library, proceeding with determining all other dependencies.
* Ensuring that the package version is stripped correctly regardless of how many digits are in the major number (an issue that appeared only after dependency retrieval was allowed to finish in its entirety)
Before:
```console
$ docker run --rm guacd cat /opt/guacamole/DEPENDENCIES …
```
> GUACAMOLE-1540: Correct automated retrieval of Docker build dependencies.

- src/common-ssh/ssh.c
- src/libguac/Makefile.am
- src/libguac/fips.c
- src/libguac/guacamole/fips.h
As discussed in https://issues.apache.org/jira/browse/GUACAMOLE-1669, this change prefers FIPS-compliant ciphers and algorithms if FIPS mode is enabled on the guacd host.
> GUACAMOLE-1669: Prefer FIPS compliant ciphers and algorithms when FIPS mode is enabled.

- src/protocols/rdp/settings.c
As discussed in https://issues.apache.org/jira/browse/GUACAMOLE-1674, this change does the following when FIPS mode is active on the guacd server:
- Disables NLA security mode when "any" mode is selected in Guacamole
- Warns the user that their selected mode is known not to work if they explicitly select NLA security mode
NOTE: Theoretically both TLS and RDP modes _should_ work, though I was not able to get RDP security mode to work with FIPS enabled, either with a Windows or XRDP remote machine.
In practice, this probably won't matter too much, since the security mode negotiation always seems to prefer TLS over RDP anyway. 
I can also disable/warn about RDP mode too, if people think that's a good idea, though I think we should probably just leave it as is for now. Maybe there's some …
> GUACAMOLE-1674: Warn about NLA mode if FIPS mode is enabled, or disable if possible.

- src/common-ssh/ssh.c
It took a while to work out what was going on here, but excluding "ext-info-c" from the list of preferred KEX algorithms precludes the ssh server from sending the `SSH_MSG_EXT_INFO`  response during negotiation, which will in turn prevent any RSA key upgrades from occurring.
Key upgrade is now working as expected (when using a libssh2 that supports key upgrades).
> GUACAMOLE-1669: Include ext-info-c in preferred KEX algorithms to ensure RSA key upgrades can happen.

- src/protocols/rdp/keymaps/cs-cz-qwertz.keymap
Fix missing char as mentioned in https://github.com/apache/guacamole-server/pull/397
> GUACAMOLE-1708: Added Czech keyboard keymap fix missing char

- src/libguac/client.c
- src/libguac/guacamole/client.h
- src/libguac/guacamole/protocol-constants.h
- src/libguac/guacamole/protocol-types.h
- src/libguac/guacamole/protocol.h
- src/libguac/guacamole/user.h
- src/libguac/protocol.c
- src/libguac/tests/protocol/guac_protocol_version.c
- src/libguac/user-handlers.c
- src/libguac/user-handlers.h
- src/libguac/user-handshake.c
- src/libguac/user.c
This pull request adds support for notifying the connection owner that another user has joined their connection. This is broken up into three commits - the first adds the underlying support for the "msg" instruction and updates the protocol accordingly, the second adds support for the "name" handshake instruction, allowing guacd to have a human-readable user name, and the third the actual support for sending the notification.
I'm sure it needs some work and clean-up, and there may be better approaches, but I took a shot :-D.
> GUACAMOLE-1293: Add support for notifying that a user has joined an existing connection.

- src/libguac/client.c
These changes make a minor correction to the usage of `__users_lock`. We were incorrectly re-acquiring the lock while it was already held for writing, and then double-releasing the lock. Overall flow is similar for both join/leave notification:
1. User joins/leaves connection and guacd enters `guac_client_add_user()` or `guac_client_remove_user()`.
2. The function in question acquires `__users_lock` for writing.
3. While the lock is held for writing, a function which calls `guac_client_for_owner()` is invoked.
4. `guac_client_for_owner()` acquires `__users_lock` for reading. The behavior of a thread doing this while it already holds the lock for writing is undefined according to POSIX (see below).
5. `guac_client_for_owner()` releases `__users_lock` (first unlock).
6. The function in …
> GUACAMOLE-1293: Do not re-acquire __users_lock while already held for writing.

- src/terminal/terminal.c
- src/terminal/terminal/terminal-priv.h
- src/terminal/terminal/terminal.h
This change adds parameter and return value documentation to all functions within libguac-terminal where this was missing. Additionally, this change:
* Updates `guac_terminal_write()` and `guac_terminal_printf()` to return the number of bytes written on success, rather than zero.
* Moves `guac_terminal_char_handler` to `terminal-priv.h` (it is not used within the public API).
> GUACAMOLE-1538: Add missing documentation for libguac-terminal.

- bin/guacctl
- configure.ac
- src/libguac/Makefile.am
- src/terminal/Makefile.am
This change:
* Bumps the version number to 1.5.0.
* Bumps the libtool version number for libguac to reflect that an interface was changed (`guac_user_info` now has a `name` member).
* Adds explicit libtool version info for libguac-terminal.
> GUACAMOLE-1604: Bump version number and libtool version info for 1.5.0.

- src/common/display.c
After the introduction of RDPGFX the joining client when joining a shared connection appears to hang (does not receive a copy of the current display) until something changes graphically within the session.
This pull request:
* Updates `guac_common_display_dup` to call `guac_protocol_send_sync` to send a sync message to all connected users which will make the joined client's display appear immediately.
> GUACAMOLE-377: Send a sync instruction to users when synchronizing surfaces.

- src/protocols/rdp/pointer.c
As kindly described by Mike Powers in [GUACAMOLE-1717](https://issues.apache.org/jira/browse/GUACAMOLE-1717), using GNOME Remote Desktop (GRD) with gaucd causes a clearly junk/corrupt cursor to be rendered. Mike tracked this down to use of uninitialized memory (`data`) in [`src/protocols/rdp/pointer.c#guac_rdp_pointer_new()`](https://github.com/apache/guacamole-server/blob/ce27936ed539872d55039b6a1b9aa54d8388659e/src/protocols/rdp/pointer.c#L35) when the call to `freerdp_image_copy_from_pointer_data()` is skipped because connecting to GRD causes `pointer->andMaskData` to be `NULL`.
As described in the ticket, the `if` guard (on line 49) causing this to happen is not necessary because FreeRDP protects against this case internally (at least in 2.0 versions), and at any rate there is a bug …
> GUACAMOLE-1717: Fix RDP cursor use of uninitialized memory

- src/protocols/rdp/gdi.c
- src/protocols/rdp/rdp.c
XRPD Connection is noticeably slow. Screen updates take time to occur and appear "laggy".
In this Pull Request we:
- Remove duplicated `include` statement.
- Consolidate frame start and last frame end timestamps when reading from rdp. 
- Change mark frames as 1 (`in_frame`) when we receive anything but an end frame from RDP (`SURFACECMD_FRAMEACTION_END`). Otherwise mark frames as 0.
> GUACAMOLE-377: Restructure rdp logic to improve graphical data rendering.

- src/protocols/rdp/user.c
This fixes a bug/race condition where the display pointer may already be freed and set to null when the user leave handler is called in the RDP code.
> GUACAMOLE-1505: Avoid null pointer dereference in RDP protocol when display is already freed.

- .github/workflows/pr-build.yml
Add PR verification job to guacamole-server. See discussion on the equivalent client PR for more: https://github.com/apache/guacamole-client/pull/811.
> GUACAMOLE-1754: Run docker build for PR CI.

- src/protocols/rdp/keymaps/hu_hu_qwertz.keymap
Change turkish 'ı' to latin 'i' in hu_hu_qwertz.keymap
related: [GUACAMOLE-1761](https://issues.apache.org/jira/browse/GUACAMOLE-1761)
> GUACAMOLE-1761: Fix hungarian keymap

- src/protocols/rdp/print-job.c
The `-c .setpdfwrite` option causes print filtering to fail if a sufficiently new version of GhostScript is installed, such as that provided by the current Alpine Linux image.
> GUACAMOLE-1755: Remove usage of .setpdfwrite for print filtering (deprecated in newer GhostScript).

- src/protocols/rdp/Makefile.am
- src/protocols/rdp/keymaps/pt_pt_qwerty.keymap
This PR adds the "pt-pt" keyboard layout. Currently only "pt-br" is included.
> GUACAMOLE-1771: add Portuguese keymap to RDP

- src/protocols/rdp/bitmap.c
- src/protocols/rdp/channels/common-svc.h
- src/protocols/rdp/channels/disp.h
- src/protocols/rdp/channels/rdpei.h
- src/protocols/rdp/gdi.c
- src/protocols/rdp/glyph.h
- src/protocols/rdp/keyboard.c
- src/protocols/rdp/plugins/guacai/guacai-messages.c
- src/protocols/rdp/settings.c
This change reapplies the same commits from #386 against `staging/1.5.2`, except that `src/protocols/rdp/channels/rdpgfx.h` does not exist in 1.5.2.
> GUACAMOLE-1636: Fixed some typo mistakes.

- src/terminal/terminal.c
This change reapplies the same commits from #381 against `staging/1.5.2`.
> GUACAMOLE-1595: Ensure all mouse buttons are initially released when terminal starts.

- src/libguac/guacamole/socket-constants.h
- src/libguac/guacamole/socket.h
- src/libguac/socket.c
This introduces a buffer for binary data to be encoded as base64 as well as a buffer for the base64 encoded data, prior to any attempt to writing it to the socket. Doing this significantly reduces the number of system calls made by the socket-fd implementation. Instead of `clock_gettime`, `pthread_mutex_rdlock`, and `pthread_mutex_unlock` being called for every 3 bytes it's now called for every ~768 bytes.
> GUACAMOLE-1776: Batch up base64 encoding to reduce syscalls.

- src/protocols/rdp/pointer.c
This change reverts part of the change made in #418 and #432, moving the memory allocation from `_aligned_recalloc()` back to `_aligned_malloc()`. In at least a couple of different versions of FreeRDP the call to `_aligned_recalloc()` is failing, causing segfaults when attempting to establish RDP connections.
> GUACAMOLE-1802: Switch memory allocation back to _aligned_malloc due to segfault caused by using _aligned_recalloc.

- bin/guacctl
- configure.ac
Bumps the versions relevant for guacd to 1.5.3.
> GUACAMOLE-1816: Bump server versions to 1.5.3.

- src/common/common/cursor.h
- src/common/cursor.c
I am seeing the issue described in [GUACAMOLE-1850](https://issues.apache.org/jira/browse/GUACAMOLE-1850) more often when testing [this change](https://github.com/apache/guacamole-server/pull/455).
Adding a mutex to control concurrent access to the surface underlying the socket appears to resolve this issue.
> GUACAMOLE-1850: Add locking around cursor to ensure cairo display is not used while being recreated.

- src/common/display.c
This change removes the errant retrieval of `guac_client` from a `guac_user` that no longer exists following merge of the batch join API via #455.
The line in question persists on `master` despite its absence from `staging/1.5.4` because the line was added as part of [GUACAMOLE-377](https://issues.apache.org/jira/browse/GUACAMOLE-377) - an in-progress change specific to `master` and not part of any 1.5.x release.
> GUACAMOLE-377: Correct guac_common_display_dup() for compatibility with batch join API.

- src/protocols/rdp/settings.c
- src/protocols/rdp/settings.h
This pull requests adds options to support the following additional certificate handling in RDP connections:
* Trust on First Use (tofu): If a host is not "known" to the underlying FreeRDP library, the certificate will be accepted and the fingerprint stored. This is equivalent to the xfreerdp command line option `/cert:tofu`.
* Fingerprint + Hash: You can provide a comma-separated list of certificate hash and fingerprint combinations that FreeRDP will accept for the connection. It's worth noting that I actually don't know the proper way to specify these at the moment, so I've been unable to actually prove this works, but I'm getting identical behavior on the xfreerdp command line as in Guacamole. I've an e-mail out to the FreeRDP mailing list to try to get some guidance on it.
> GUACAMOLE-1332: Add support for certificate fingerprints and auto-accept.

- src/protocols/kubernetes/client.c
- src/protocols/rdp/client.c
- src/protocols/ssh/client.c
- src/protocols/telnet/client.c
- src/protocols/vnc/client.c
The user promotion thread is started before the client initialization is fully complete, so we should not expect that all client resources will be available when the pending handlers run. 
If the resources _are_ uninitialized, the pending handlers can still run successfully because there isn't any state to sync anyway.
> GUACAMOLE-1846: Check for NULLs before attempting to sync state in join pending handlers.

- src/common-ssh/tests/Makefile.am
- src/common/tests/Makefile.am
- src/protocols/rdp/tests/Makefile.am
The build is currently failing on some build environments with an error like the following:
```
...
#8 157.1 /usr/bin/ld: fs/test_rdp-normalize_path.o: undefined reference to symbol 'PRIV_guac_mem_alloc'
#8 157.1 /usr/bin/ld: /build/guacamole-server/src/libguac/.libs/libguac.so.21: error adding symbols: DSO missing from command line
...
```
This is because unit tests leveraging the new functions need to be explicitly linked against libguac. These changes add such linkage to all tests that were updated for GUACAMOLE-1867.
> GUACAMOLE-1867: Explicitly link unit tests requiring libguac.

- src/libguac/mem.c
Oops (this broke the verification build for #465).
> GUACAMOLE-1867: Fix typo in memory convenience functions (ssize_t -> size_t).

- src/common-ssh/user.c
This change updates the only code specific to `master` that still pointed at good ol' `free()` and `strdup()` following the merge of #462, thankfully all relevant to the same JIRA issue ([GUACAMOLE-1290](https://issues.apache.org/jira/browse/GUACAMOLE-1290)).
Outside of this, the only other old code that remains using `free()`, `malloc()`, etc. is code that deals with memory allocated or freed by a third-party library.
> GUACAMOLE-1290: Migrate SSH certificate auth support to new memory management functions.

- src/libguac/encode-webp.c
Those will be made nodiscard at some point anyway.
Issue GUACAMOLE-1875
> GUACAMOLE-1875: Check return values of WebP API functions.

- configure.ac
Fixing https://issues.apache.org/jira/projects/GUACAMOLE/issues/GUACAMOLE-1869
Aligning library names to contain a space after the name.
> GUACAMOLE-1869: Aligned library names of ./configure output

- bin/guacctl
- configure.ac
- src/libguac/Makefile.am
- src/terminal/Makefile.am
This change updates the version numbers within guacamole-server to 1.5.4. [Library soversion numbers](https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html) have also been updated to reflect the nature of changes made:
* libguac contains changes to the `guac_client` structure that affect structure member offsets. Established code linking against libguac would need to be rebuilt.
* libguac-terminal adds a new function (`guac_terminal_sync_users()`) but otherwise presents the exact same API and ABI.
> GUACAMOLE-1886: Bump version numbers / soversions for 1.5.4.

- src/protocols/rdp/channels/pipe-svc.c
- src/protocols/rdp/client.c
This PR attempts to address the race condition associated with the RDP client join handler and the pipe svc attempt to access the available_svc member of the rdp_client data structure. I've taken both suggestions in one of the Jira tickets for 1) acquiring the overall lock and 2) doing a NULL check around available_svc before attempting to access it.
It's worth noting that simply acquiring the lock on its own within the guac_rdp_join_pending_handler() function does not actually resolve the problem - the NULL check is required. So, I'm not sure in the lock is actually worth anything, or if there's somewhere else (around the SFTP connection, maybe?) that the lock should also be acquired?
> GUACAMOLE-1140: Fix RDP pipe svc race condition with lock and NULL check.

- configure.ac
- src/libguac/Makefile.am
I've fixed the build issues related to librt for Ubuntu 22.04.
> GUACAMOLE-1892: Fix the build issues related to librt for Ubuntu 22.04.

- src/common/surface.c
I've fixed a segfault issue related to the uninitialized memory when resizing the browser window.
> GUACAMOLE-1900: Fix a segfault issue caused by uninitialized memory.

- src/protocols/vnc/cursor.c
set rcMask to NULL to prevent double-free errors occuring in libvncclient 0.9.13 and up
> GUACAMOLE-1903: set rcMask to NULL

- bin/guacctl
- configure.ac
This change bumps the guacamole-server versions to 1.5.5. As far as I can tell, there are no changes (and no Jira issues slated to be added to 1.5.5) that would require bumping libguac and/or libguac-terminal.
> GUACAMOLE-1906: Bump guacamole-server versions to 1.5.5.

- src/common/clipboard.c
As noted on [GUACAMOLE-1917](https://issues.apache.org/jira/browse/GUACAMOLE-1917), these changes add the `guac_socket_flush()` call missing from the internals of `guac_common_clipboard_send()`, ensuring changes to the clipboard don't get stuck waiting until something else happens to flush the socket.
> GUACAMOLE-1917: Ensure remote changes to clipboard are immediately received by connected users.

- src/common/surface.c
These changes correct the incorrect socket and the logic error in `guac_common_surface_dup()` that are currently preventing the multitouch attribute from being correctly synced at all ([GUACAMOLE-1918](https://issues.apache.org/jira/browse/GUACAMOLE-1918)). The multitouch attribute should be synced for the default layer (not for all layers _except_ the default) and must be sent along the provided socket (not the surface's socket).
> GUACAMOLE-1918: Sync multitouch attribute for default surface.

- src/libguac/client.c
`guac_rwlock_init()` already initializes these keys - these extra calls will slowly eat up system resources until `pthread_key_create()` calls start failing. 
Removing fixes that issue.
> GUACAMOLE-1920: Remove vestigial pthread_key_create calls during client initialization.

- src/libguac/guacamole/socket-ssl.h
- src/libguac/socket-ssl.c
When TLS is turned on the file descriptor for the socket does not use locking when writing to it. It results in corrupted guacamole instructions being written to the stream when there are multiple connected clients.
This adds a mutex in the same manner done in `socket-fd.c`.
> GUACAMOLE-1910: Add locking around TLS socket

- src/protocols/vnc/argv.h
- src/protocols/vnc/user.c
This simple change processes the `argv` handler for the VNC protocol even when the connection is read-only, which is required to prompt for credentials for read-only connections. As these are the only parameters that are processed by the `argv` handler, there is no additional impact on the code.
It's worth noting that, if other parameters are added in the future, the `argv` handler may need to check the `read_only` parameter and make decisions about which parameters should be allowed to be processed and which should be ignored or blocked.
> GUACAMOLE-1921: Process argv handler even when the connection is read-only.

- src/libguac/Makefile.am
After the changes in #484, the version of libguac needs to be bumped.
> GUACAMOLE-1906: Bump soversion for liguac after API changes.

- src/guacenc/ffmpeg-compat.c
- src/guacenc/ffmpeg-compat.h
- src/guacenc/video.c
This back-ports the changes previously committed in #399 to the `staging/1.5.5` branch for the next bugfix release.
> GUACAMOLE-1714: Back-port of const parameters of ffmpeg 5.0.

- src/protocols/rdp/client.c
- src/protocols/rdp/input.c
- src/protocols/rdp/keyboard.c
- src/protocols/rdp/rdp.c
- src/protocols/rdp/rdp.h
Resolve authentication timeout and deadlock issues. There was a timeout occurring approximately 12 seconds into an RDP connection when using NLA and resources were not properly being cleaned up.
To address this, `guac_argv_stop` has been introduced. It ensures that when a client disconnects, any threads waiting for user input (such as username or password), can effectively abort their wait, preventing the connection from hanging indefinitely.
A deadlock has also been mitigated by modifying the lock state to allow read access to other threads when it is safe to do so.
> GUACAMOLE-1732: Prevent deadlock and enhance cleanup in RDP client.

- src/protocols/rdp/rdp.c
This pull request corrects issues identified by Coverity Scan related to a misunderstanding of lock upgrading in `rwlock.h`. I refined the locking logic to ensure consistent lock acquisition and release, following the intended use of the `rwlock.h`
> GUACAMOLE-1732: Free dangling locks and correct and remove unnecessary locks.

- src/guacd-docker/bin/build-all.sh
Pull request based on discussion [here](https://lists.apache.org/thread/yoqfy9s6bfvcsgccc33kylgyk9h7pwko). 
It is difficult to dynamically determine build options based on a given architecture from within a Dockerfile without requiring manually passing in the architecture type as an argument during the build process. Instead, this proposed approach uses the fact that a build script is used to actually build the dependencies and checks the architecture there. With this information it generates a list of overrides which are appended to the end of the `install_from_git` functions. Options are processed in order so by appending them to the end, they will override any options provided in the main Dockerfile. This guarantees the build process succeeds (even if the user provides bad options in …
> GUACAMOLE-1374: Guacamole in Docker on ARM

- src/libguac/rwlock.c
Corrected flag comparison in "guac_rwlock_acquire_write_lock" function
> GUACAMOLE-1940: Correct flag comparison in "guac_rwlock_acquire_write_lock" function

- src/protocols/vnc/settings.c
- src/protocols/vnc/settings.h
- src/protocols/vnc/vnc.c
Adds the guacd side support for passing on quality and compression settings to the libvncclient library.
> GUACAMOLE-1760: Add guacd support for setting VNC compression and quality.

- src/terminal/terminal.c
Remove display->margin on mouse position to avoid offset between selection and actual mouse position.
> GUACAMOLE-1944: Remove display margin on mouse position

- configure.ac
This takes care of a some issues in `configure.ac` that cause some build issues.
I'm still a bit stumped by the original issue, though, that is mentioned in the ticket - when you run `./configure --with-libavcodec=no`, several strange things happen:
* PANGO isn't found
* RDP, SSH, and Telnet don't build
I'm having a very hard time tracking down what's going on - if anyone can pinpoint the issue, I'd be grateful. It's almost as if there's some mis-matched quotes or brackets or something that are triggered specifically in the case of libavcodec being disabled. Interestingly, if I removed the libavcodec section from `configure.ac`, the behavior follows to the next block (libavformat).
> GUACAMOLE-1719: Fix errors in autoconf file that cause strange build behavior

- src/protocols/vnc/settings.c
- src/protocols/vnc/settings.h
- src/protocols/vnc/vnc.c
Finishing up the work that @stefan-esq started on #327 - this should tie up the final changes for adding the server-side setting for `disable-remote-input` on the VNC protocol.
This closes #327.
> GUACAMOLE-1267: Add VNC setting 'disable-remote-input'

- src/common-ssh/ssh.c
- src/libguac/Makefile.am
- src/libguac/guacamole/socket-tcp.h
- src/libguac/guacamole/string.h
- src/libguac/guacamole/wol-constants.h
- src/libguac/guacamole/wol.h
- src/libguac/socket-tcp.c
- src/libguac/string.c
- src/libguac/wol.c
- src/protocols/rdp/rdp.c
- src/protocols/ssh/ssh.c
- src/protocols/telnet/telnet.c
- src/protocols/vnc/vnc.c
This PR adds to the Wake-on-LAN functionality, implementing a new function that checks the connection to the destination server both before sending the WOL packet and, again, after sending the packet. If the host responds before sending the WOL packet, there is no need to actually send the WOL packet. If the packet does get sent, then the function will attempt to connect, then wait for the specified time period and then re-try the connection.
As a by-product of this implementation, I've also added a couple of other things:
* Centralized the TCP socket connection functionality into a common function, and updated the protocols that use it (SSH and Telnet, at the moment) to use that function. I'm not sure I got this in the right place, so if there are opinions about where to move it, I'm …
> GUACAMOLE-1686: Make WOL functionality capable of testing connectivity to the server.

- src/libguac/wol.c
This fixes an issue that Coverity identified that I missed the first time around with a resource leak when failing to close file descriptors before they go out of scope.
> GUACAMOLE-1686: Fix fd resource leak in WoL code.

- src/protocols/rdp/channels/rail.c
This implements some basic logging and client handling (abort) for situations where a RAIL command is not executed successfully. Without this change, the RAIL session just hangs open until the server times out and closes the RDP connection, which can take several minutes.
> GUACAMOLE-1084: Implement basic handling for unsuccessful RAIL execution results.

- src/guacenc/video.c
Deprecated avcodec_close was removed in FFMPEG 7.0
> GUACAMOLE-1952: Add compatibility with FFMPEG 7.0

- src/protocols/rdp/channels/rail.c
- src/protocols/rdp/channels/rail.h
- src/protocols/rdp/client.c
- src/protocols/rdp/rdp.h
This is a really basic update for the Guacamole RAIL channel that handles situations where RAIL windows are minimized by simply immediately sending the `SC_RESTORE` command for that window back to the RDP server, causing the window to immediately re-appear. This resolves, at a very basic level, the issue with RAIL windows that are minimized becoming inaccessible within the Guacamole interface.
Looking at both the MS-RDPERP specification and the xfreerdp client, I suspect there is a lot more potential for some really cool functionality within the RAIL channel that could be implemented within Guacamole - like the ability to track what RAIL windows are open for a particular client, perhaps even open them in new/separate windows, and perhaps even integrate with the current multi-connection …
> GUACAMOLE-1231: Implement basic support for restoring minimized RAIL windows

- src/terminal/select.c
- src/terminal/terminal.c
- src/terminal/terminal/terminal-priv.h
Allows selecting a word on double-click and a complete line on triple-click.
Based on the unmaintained PR by @Saiyeux (https://github.com/apache/guacamole-server/pull/406) :
- All "rewritten" functions have been removed in favor of existing functions.
-> Code simplification.
-> Fixes several unexpected behaviors when scrolling upwards.
- The following characters are now considered part of a "word": [0-9\\/A-Za-z_\\~\\&\\-\\.\\?\\\\%=:\$]
-> Allows selecting an IP address, a path or URL (ex: https://www.test.tld/file.php?param1=value1&param2=value%202)
- Improved condition in the guac_terminal_select_update (select.c) function to allow selecting a "word" of a single character on double-click (no impact on single-click).
> GUACAMOLE-192: Select word in terminal on double click

- Dockerfile
- configure.ac
- src/guacd-docker/bin/build-all.sh
- src/libguac/guacamole/string.h
- src/libguac/string.c
- src/protocols/rdp/Makefile.am
- src/protocols/rdp/bitmap.c
- src/protocols/rdp/channels/cliprdr.c
- src/protocols/rdp/channels/rdpsnd/rdpsnd-messages.c
- src/protocols/rdp/color.c
- src/protocols/rdp/gdi.c
- src/protocols/rdp/glyph.c
- src/protocols/rdp/glyph.h
- src/protocols/rdp/input.c
- src/protocols/rdp/keyboard.c
- src/protocols/rdp/plugins/channels.c
- src/protocols/rdp/plugins/channels.h
- src/protocols/rdp/plugins/guacai/guacai.c
- src/protocols/rdp/pointer.c
- src/protocols/rdp/pointer.h
- src/protocols/rdp/rdp.c
- src/protocols/rdp/rdp.h
- src/protocols/rdp/settings.c
Refactored to support both FreeRDP 2 and 3.
- Added version checking for FreeRDP 3.x and fallback to 2 if 3 doesn't exist
- Additional checks introduced for various FreeRDP 3.x feature support
- `_aligned_free` and `_aligned_malloc` renamed to `winpr_aligned_free` and `winpr_aligned_malloc`
- `ReadColor` and `WriteColor` renamed to `FreeRDPReadColor` and `FreeRDPWriteColor`
- Various `CLIPRDR` properties moved to  `CLIPRDR_HEADER common` struct for `CLIPRDR` structs. 
- Required use of getter/setter functions interacting with `rdpSettings` 
- `freerdp_settings_set_pointer`, `freerdp_settings_set_bool`, `freerdp_settings_set_string`, freerdp_settings_set_uint32, `freerdp_settings_get_pointer_writable`, `freerdp_settings_get_bool`, `freerdp_settings_get_string`, …
> GUACAMOLE-1026: Add support for FreeRDP3.

- src/terminal/select.c
- src/terminal/terminal/types.h
This selection :
Clipboard content before this code:
```c
/* Pass through start/end coordinates if they are already in the expected
* order, adjusting only for final character width */
if (terminal->selection_start_row < terminal->selection_end_row
|| (terminal->selection_start_row == terminal->selection_end_row
&& terminal->selection_start_column < terminal->selection_end_column)) {
*start_row = terminal->selection_start_row;
*start_col = terminal->selection_start_column;
*end_row   = terminal->selection_end_row;
*end_col   = terminal->selection_end_column + terminal->selection_end_width - 1;
}
```
And now:
```c
/* Pass through start/end coordinates if they are already in the expected
* order, adjusting only for final character width */
if (terminal->selection_start_row < …
```
> GUACAMOLE-1632: Fill null chars before last printable char with spaces

- src/terminal/terminal-handlers.c
- src/terminal/terminal.c
- src/terminal/terminal/terminal-priv.h
Add support of alternate screen buffer for tools like less/vi/man/...
Before:
After:
> GUACAMOLE-1633: Add support of alternate screen buffer

- configure.ac
Resolved `-Werror=unused-but-set-variable` compilation errors in EL environments by explicitly using affected variables. Improved verification of `const` usage in FreeRDP's `GetPluginData`, ensuring compatibility across versions.
> GUACAMOLE-1026: Improved FreeRDP3 Configuration Checks for el7 and el8 Build Environments

- src/protocols/rdp/keymaps/ja_jp_qwerty.keymap
Some Japanese IME keys seem to be missing.
I tested with Ubuntu 22.04 as client and Windows 11 as server and it worked fine!
(Edit: I misunderstood the format of keymap, so I fixed it.)
> GUACAMOLE-520: Add mapping of Japanese IME keys.

- src/terminal/terminal-handlers.c
- src/terminal/terminal.c
- Add support of 'S' and 'T' CSI sequences (scroll up/down by amount).
- Force display flush when scrolling to avoid conflict when cursor_commit use the set_collumns function which change the operation_type.
> GUACAMOLE-1256: Correct terminal scroll with text editors.

- src/protocols/rdp/pointer.c
CodeQL has flagged a potential integer overflow so I used `guac_mem_ckd_mul_or_die()` to safely multiple the values.
> GUACAMOLE-1971: Safely multiply values to be used for memory allocation.

- src/common/common/display.h
- src/common/display.c
- src/protocols/rdp/channels/disp.c
- src/protocols/rdp/channels/disp.h
- src/protocols/vnc/client.c
- src/protocols/vnc/display.c
- src/protocols/vnc/display.h
- src/protocols/vnc/input.c
- src/protocols/vnc/input.h
- src/protocols/vnc/settings.c
- src/protocols/vnc/settings.h
- src/protocols/vnc/user.c
- src/protocols/vnc/vnc.c
- src/protocols/vnc/vnc.h
This PR takes a crack at implementing the recently-added libvncclient support for `SendExtDesktopSize()`, which should allow Guacamole as a VNC client to send its size to VNC servers that support such functionality and have the display dynamically resized.
I'm creating as a draft for the moment since I have not actually tested the functionality. Among the things I'm not sure of:
* The RDP protocol contains a `resolution` setting which specifies the DPI resolution of the screen. I don't see any reason to try to mirror this into the VNC protocol, as I don't think VNC actually does anything with it (I think the DPI is fixed), but if I'm wrong let me know and I can add that support and try to update the code accordingly.
* In the Jira issue …
> GUACAMOLE-1196: Implement support for VNC display size updates

- configure.ac
- src/protocols/vnc/display.c
- src/protocols/vnc/input.c
- src/protocols/vnc/user.c
- src/protocols/vnc/vnc.c
This attempts to fix the build issues with older version of libvncserver by detecting support for various definitions and data structure members at compile time and disabling resize features that aren't supported.
> GUACAMOLE-1196: Detect libvnc support for various resize-related commands at compile time.

- configure.ac
- src/protocols/vnc/display.c
Correct a couple of my mistakes - first, I used the wrong check in `configure.ac` to test for the definition of the data type, and then I forgot to commit a change to `display.c` in the last pull request. This fixes both issues, and I've tested the compile on both Rocky 8 with libvnc < 0.9.13, and on Rocky 9 with a self-compiled libvnc from git.
> GUACAMOLE-1196: Correct checks for RFB resize message support.

- src/protocols/rdp/settings.c
- src/protocols/rdp/settings.h
This first PR in an expected set of them to allow for adjusting the connection timeouts for the various protocols. This allows adjusting the TcpAckTimeout within the FreeRDP settings, setting the timeout to something other than the 9 seconds that the FreeRDP library appears to default to.
> GUACAMOLE-600: Add support for the FreeRDP TcpAckTimeout setting

- src/common-ssh/common-ssh/ssh.h
- src/common-ssh/ssh.c
- src/libguac/guacamole/socket-tcp.h
- src/libguac/guacamole/wol-constants.h
- src/libguac/guacamole/wol.h
- src/libguac/socket-tcp.c
- src/libguac/wol.c
- src/protocols/rdp/rdp.c
- src/protocols/rdp/settings.c
- src/protocols/rdp/settings.h
- src/protocols/ssh/settings.c
- src/protocols/ssh/settings.h
- src/protocols/ssh/ssh.c
- src/protocols/telnet/telnet.c
- src/protocols/vnc/settings.c
- src/protocols/vnc/settings.h
- src/protocols/vnc/vnc.c
This pull request adds support for setting the connection timeout for SSH and SFTP connections via connection parameters.
> GUACAMOLE-600: Add support for setting SSH and SFTP timeouts.

- src/protocols/rdp/rdp.c
- src/protocols/rdp/settings.c
- src/protocols/rdp/settings.h
- src/protocols/ssh/ssh.c
- src/protocols/vnc/settings.c
- src/protocols/vnc/settings.h
- src/protocols/vnc/vnc.c
This pull request fixes up a couple of issues with public key imports for SSH/SFTP connections:
* Adds the required parameters so that public keys can be used for SFTP connections in addition to SSH connections.
* Moves the code that checks for the presence of the public key inside the block that checks for private key authentication. I'm still a little fuzzy on the purpose of importing a public key, but, if I understand the libssh2 functions correctly, there's no time that you'd want to try to import or use a public key if you weren't also authenticating with a private key. The code, as merged before, imported the public key regardless of whether a private key was present, and the `if/else` logic use also messed up the detection between public key and password-based authentication.
> GUACAMOLE-1290: Add SFTP support for public keys and correct SSH protocol issue.

- configure.ac
- src/guacd/daemon.c
- src/guacd/proc-map.h
Applying the patch provided on the Jira issue.
> GUACAMOLE-663: Set pthread stack size for guacd

- configure.ac
Previously, the name of the library would change depending on which version is installed:
```
$ ./configure
...
------------------------------------------------
guacamole-server version 1.5.5
------------------------------------------------
Library status:
freerdp3 ............ yes
pango ............... yes
libavcodec .......... yes
...
```
and there was no output for the "disabled" case:
```
...
------------------------------------------------
guacamole-server version 1.5.5
------------------------------------------------
Library status:
freerdp ............ 
pango ............... yes
libavcodec .......... yes
...
```
Here, the library name remains constant while version notes are included to the side:
```
$ ./configure
...
------------------------------------------------ …
```
> GUACAMOLE-1026: Correct and clean up FreeRDP presence/absence reporting by configure.

- src/common-ssh/ssh.c
- src/libguac/Makefile.am
- src/libguac/guacamole/tcp.h
- src/libguac/tcp.c
- src/libguac/wol.c
- src/protocols/telnet/telnet.c
This change slightly alters the `guac_socket_tcp_connect()` function and corresponding header such that:
* It does not reuse the `guac_socket_*` namespace (these functions don't involve `guac_socket`).
* The documentation notes that `guac_error` is used to communicate error details.
* The header file includes a `@file` comment (apparently necessary for Doxygen to include the docs at all).
> GUACAMOLE-600: Refactor guac_socket_tcp_connect() to guac_tcp_connect(), as it does not involve guac_socket.

- src/terminal/buffer.c
- src/terminal/select.c
- src/terminal/terminal-handlers.c
- src/terminal/terminal.c
- src/terminal/terminal/buffer.h
In the case of selecting multiple lines, do not add \n if the line is not really finished.
**Changes:**
- Correct buffer_row length on terminal init.
- Using the last column of the buffer_row (out of screen) to store a 1 if the word wrap was forced (0 is written when initializing the row).
- In case of selection on several lines, we add a \n only if the value of the last column is 0.
> GUACAMOLE-1586: Don't add \n in clipboard if the line isn't finished.

- src/libguac/tcp.c
Okay, I think I've got the issue figured out after some Google Research on how to handle non-blocking sockets in Linux. Let me know if this looks sane or needs any work. I re-tested and am able to establish SSH connections...
> GUACAMOLE-600: Correct handling of non-blocking socket for timeout.

- src/protocols/vnc/display.c
- src/protocols/vnc/vnc.h
VNC resizing was not working for me - I'm getting this message every time I attempt to resize the window, as well as on initial load:
`ERROR:	Screen has not been initialized, cannot send resize.`
I dug into it, and I found two problems:
1. The RFB client screen ID was never set, which caused any message from the server specifying a screen size to be ignored by the client.
2. The guacamole display was never resized after sending the resize request to the VNC server.
I've fixed these two issues, though I'm not sure if this is the cleanest way of doing it. 
@necouchman mind having a look? I know you're much more familliar with this code than me.
> GUACAMOLE-1196: Fix VNC resizing behavior.

- src/protocols/vnc/display.c
Before, I was immediately resizing the guac display size right after sending the resize request to the server. This works fine as long as the VNC server actually _does_ the resize as requested, but we can't assume that it will. 
This change updates it to only update the display size when the screen size has changed.
> GUACAMOLE-1196: Resize guacamole display only when VNC screen size is changed by the server.

- src/protocols/vnc/display.c
Third time's the charm, I hope.
@necouchman already had all the proper configure checks in his code but I somehow managed to leave them out🤦‍♂️.
> GUACAMOLE-1196: Fix compile issues with older VNC client versions where screen isn't defined.

- configure.ac
- src/protocols/rdp/rdp.c
Plugins were not working properly when building Guacamole with FreeRDP3 due to a change in how they are loaded. This PR implements the LoadChannels callback function for loading plugins.
https://github.com/FreeRDP/FreeRDP/wiki/FreeRDP3-migration-notes
> Channel loading has been moved from PreConnect to LoadChannels. This has a default implementation in client/common and only step required is removing calls to freerdp_client_load_addins
> GUACAMOLE-1026: Use LoadChannels callback method to load plugins with FreeRDP3.

- src/protocols/vnc/display.c
Per https://libvnc.github.io/doc/html/structrfb_client.html#a46b40d74f04da6f6c302370156cc46c0, the screen field of the VNC client should only be used for setting intended dimensions, not reading updated / current dimensions.
> GUACAMOLE-1196: Read VNC dimensions directly from the client, not the screen.

- src/terminal/buffer.c
Running `screen` is currently failing because we're a smidge too strict in this check.
> GUACAMOLE-377: Correct regression in terminal assertion (too strict by one column).

- src/terminal/terminal-handlers.c
This is otherwise currently breaking the build on Rocky Linux and presumably others.
> GUACAMOLE-377: Add missing include for errno.

- src/terminal/terminal-handlers.c
- src/terminal/terminal.c
- src/terminal/terminal/terminal-priv.h
The contents of the alternative buffer are still visible when returning to the normal buffer.
Example with vi:
After close it (selection remains too):
I reused `guac_terminal_redraw_default_layer` function on `apply_color_scheme` and `apply_font` functions because the code is the same.
> GUACAMOLE-377: Fix issue where display content is not updated when switching back to normal buffer.

- src/protocols/rdp/gdi.c
With freerdp >= 3.8.0, we can't resize with "display-update":
```
guacd[609180]: DEBUG:   Display update channel will be used for display size changes.
guacd[609180]: DEBUG:   {Microsoft::Windows::RDS::DisplayControl:16} OnOpen=(nil), OnClose=0x7f40b610b150
guacd[609180]: DEBUG:   Server resized display to 768x583
GUAC_ASSERT in guac_rdp_gdi_end_paint() failed at gdi.c:102.
guacd[609080]: INFO:    Connection "$3ec11dae-60d9-4820-9028-01a10f4e95f4" removed.
guacd[609080]: DEBUG:   Unable to request termination of client process: No such process 
guacd[609080]: DEBUG:   All child processes for connection "$3ec11dae-60d9-4820-9028-01a10f4e95f4" have been terminated. 
```
Caused by this bugfix in freerdp: https://github.com/FreeRDP/FreeRDP/pull/10488
Freerdp triggers EndPaint first when …
> GUACAMOLE-1997: Fix issue on screen resize with freerdp >= 3.8.0.

- src/terminal/display.c
- src/terminal/terminal.c
Allows better synchronization between the buffer and the display, which avoids "mixed" displayed data when highlighting braces, parentheses and others in vi.
Seems to fix a latency issue when scrolling up in less.
> GUACAMOLE-1256: Fix a display issue when scrolling up in vi as well as latency in less.

- configure.ac
- src/protocols/vnc/display.c
- src/protocols/vnc/input.c
- src/protocols/vnc/user.c
- src/protocols/vnc/vnc.c
- src/protocols/vnc/vnc.h
This pull request brings the VNC resize support in Guacamole in line with the RFB standard:
* The client must receive an `ExtendedDesktopSize` rectangle message from the server before trying to send its size to the server. Unless and until this has been received, no `SetDesktopSize` message can be sent, and sending it will either be ignored by the server or cause the server to drop the connection. In libvncclient, the receipt of this message initializes the `client->screen` data structure, so we test for that in order to find out if the message has been sent and we are allowed to send the client size to the server.
* This makes the initial sizing of the remote desktop to the client size a bit challenging, since we cannot send that initial message until we've received and processed at …
> GUACAMOLE-1196: Correct VNC resize to conform to the RFB standard.

- src/common-ssh/ssh.c
* Added AES GCM ciphers to the FIPS compliant cipher list
* Added some code to check if the hardcoded FIPS compliant ciphers are really supported by libssh2
> GUACAMOLE-2012: Fix SSH connection to FIPS servers which only offer AES GCM

- src/common/clipboard.c
- src/common/common/clipboard.h
- src/protocols/kubernetes/kubernetes.c
- src/protocols/kubernetes/settings.c
- src/protocols/kubernetes/settings.h
- src/protocols/rdp/channels/cliprdr.c
- src/protocols/rdp/channels/cliprdr.h
- src/protocols/rdp/client.c
- src/protocols/rdp/settings.c
- src/protocols/rdp/settings.h
- src/protocols/rdp/user.c
- src/protocols/ssh/settings.c
- src/protocols/ssh/settings.h
- src/protocols/ssh/ssh.c
- src/protocols/telnet/settings.c
- src/protocols/telnet/settings.h
- src/protocols/telnet/telnet.c
- src/protocols/vnc/client.c
- src/protocols/vnc/clipboard.c
- src/protocols/vnc/settings.c
- src/protocols/vnc/settings.h
- src/protocols/vnc/user.c
- src/terminal/terminal.c
- src/terminal/terminal/terminal.h
[Jira Discussion](https://issues.apache.org/jira/browse/GUACAMOLE-2002)
> GUACAMOLE-2002: Allow connection clipboard limits to be configured.

- src/protocols/rdp/settings.c
This change corrects the regression in handling of FreeRDP 3.x performance flags. Apparently, we simply inverted the logic through the magic of copypasta.
> GUACAMOLE-1026: Correct inverted performance flag logic.

- src/libguac/display-flush.c
- src/libguac/display-plan.c
- src/libguac/display-plan.h
- src/libguac/display-worker.c
The `END_FRAME` operation was previously used to notify workers that the frame has ended, but since the receiving worker needs to check and push that operation back onto the queue if other workers are still busy, it's essentially unnecessary _and_ results in several workers spinning as they pass `END_FRAME` around until all others are done.
It's sufficient to simply check whether the operation queue is empty and no other workers are active.
Recommend ignoring whitespace in the diff - much of this is a change in indentation.
> GUACAMOLE-377: Remove use of END_FRAME operation from guac_display.

- src/protocols/rdp/settings.c
This PR fixes an issue where RDP performance flags set in Guacamole were being ignored by newer versions of FreeRDP.
The problem occurs because FreeRDP now defaults to automatic detection of connection type, which causes the server to ignore explicitly set performance flags. 
I am currently testing this but it seems by explicitly setting the connection type to LAN, we can ensure that our performance flags are properly respected.
> GUACAMOLE-1026: Set ConnectionType to LAN to prevent auto-detection in FreeRDP from overriding performance flags.

- src/libguac/Makefile.am
This change updates the libguac soversion (`-version-info`) to match the changes made since 1.5.5, following the libtool documentation for maintaining this value: 
https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html
> GUACAMOLE-1980: Bump libguac soversion for changes since 1.5.5 (interfaces changed).

- src/protocols/vnc/display.c
This updates a couple of the log levels for display resize messages in the VNC protocol to `GUAC_LOG_DEBUG` so that default logging is a little less verbose.
> GUACAMOLE-2062: Adjust log level for display resize messages.

- src/libguac/display-render-thread.c
- src/libguac/flag.c
From [the relevant comment in JIRA](https://issues.apache.org/jira/browse/GUACAMOLE-2063?focusedCommentId=17954770&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17954770):
> Part of the fix already committed needs to acquire the proper lock before checking `render_thread->state.value`. As reported by Coverity, the following block of code:
>
> ```c
> /* Use explicit frame boundaries whenever available */
> if (render_thread->state.value & GUAC_DISPLAY_RENDER_THREAD_STATE_FRAME_READY) {
>
>     rendered_frames = render_thread->frames;
>     render_thread->frames = 0;
>
>     guac_flag_clear(&render_thread->state,
>               GUAC_DISPLAY_RENDER_THREAD_STATE_FRAME_READY
>             | GUAC_DISPLAY_RENDER_THREAD_STATE_FRAME_MODIFIED);
> …
```
> GUACAMOLE-2063: Ensure state flag lock is acquired before checking flag value.

- src/terminal/display.c
The previously accepted workaround affects scrolling to both directions. That is an overhead because
- The main reason to introduce that patch was scrolling to the beginning of texts. The other scrolling issues either were fixed by #565 or were insignificant.
- Like it was before #554 users will complain about significant performance degradation when dumping big texts files. Tested!
I suggest to apply the workaround only for the case when you scroll to the beginning of texts. In most cases it is done manually via the ARROW UP key where performance degradation is not so visible.
> GUACAMOLE-1256: Tweak the workaround to avoid latency when dumping big text files.

- Dockerfile
- configure.ac
This change alters the guacamole-server build such that it prefers FreeRDP 2.x and warns that support for 3.x is currently experimental if only 3.x is available.
The Docker build has also been modified to install FreeRDP 2.x instead of 3.x.
> GUACAMOLE-1026: Mark FreeRDP 3.x as currently experimental.

- src/protocols/rdp/settings.c
- src/protocols/ssh/settings.c
- src/protocols/telnet/settings.c
- src/protocols/vnc/settings.c
Proposed fix for [GUACAMOLE-2113](https://issues.apache.org/jira/browse/GUACAMOLE-2113)
- Removed extra comma(,) in guac_user_log function calls so that the full message is logged.
- Added a comma for clarity with in the log message for RDP.
Results after local testing:
```
For VNC
guacd[273689]: WARNING: Wake on LAN was requested, but no MAC address was specified.  WoL will not be sent.
For SSH
guacd[299356]: WARNING: WoL was enabled, but no MAC address was provided.  WoL will not be sent.
For Telnet
guacd[298001]: WARNING: Wake on LAN was requested, but no MAC address was specified.  WoL will not be sent.
For RDP
guacd[299506]: WARNING: WoL requested, but no MAC address specified.  WoL will not be sent.
```
> GUACAMOLE-2113: Improve warning when WoL is enabled but no MAC address is provided

- configure.ac
- src/guacd/Makefile.am
- src/guacd/systemd/guacd.service.in
This adds an additional configure argument `--with-systemd-user`.
I've tried to follow the pattern of how other configure arguments and variables are defined. The indentation style for the changes in Makefile.am is taken from [an example in the Automake manual](https://www.gnu.org/software/automake/manual/html_node/Scripts.html), using an additional space character to indent a multi-line command.
Here are some examples which show the additional configure output:
```
$ ./configure --help | grep -A2 with-systemd-user
--with-systemd-user=<username>
the user configured in the systemd unit to run guacd
[default=daemon]
$ 2>/dev/null ./configure | grep -B1 'Systemd user:'
Systemd units: no
Systemd user: no
$ 2>/dev/null ./configure --with-systemd-dir=/etc/systemd/system | grep -B1 'Systemd …
```
> GUACAMOLE-1981: Add configure argument for systemd user

- src/protocols/rdp/channels/rail.c
This PR removes the re-showing of HIDDEN windows, instead only re-showing MINIMIZED windows, which fixes issues with dialog boxes that have drop-downs that won't go away.
> GUACAMOLE-2068: RAIL should only re-show minimized windows.

- src/protocols/rdp/channels/rail.c
- src/protocols/rdp/rdp.c
- src/protocols/rdp/settings.c
This is likely the first of a couple of changes to correct issues with RAIL support in FreeRDP3 and in Guacamole's support of GFX. I finally stumbled upon the reason that the FreeRDP3 changes had broken RAIL support - the RAIL plugin was being loaded _only_ the `PreConnect` callback (`rdp_freerdp_pre_connect()`), and not in the `LoadChannels` callback (`rdp_freerdp_load_channels()`). The change in FreeRDP (https://github.com/FreeRDP/FreeRDP/commit/ef8c9e48e8acf61e16cb9fd547799067c87b20da) that broke this unified the reloading of channels into a single function that disconnected and closed all of the channels and then used the `LoadChannels` callback to reload all of them. Since RAIL was not being processed through that callback, it would get dropped but never reconnected. This moves the …
> GUACAMOLE-2072: RAIL plugin should be loaded in the LoadPlugins callback.
