apache/guacamole-server

configure.ac, src/libguac/guacamole/protocol-types.h, src/protocols/rdp/Makefile.am, src/protocols/rdp/audio_input.c, src/protocols/rdp/audio_input.h, src/protocols/rdp/client.c, src/protocols/rdp/compat/winpr-stream.c, src/protocols/rdp/dvc.c, src/protocols/rdp/dvc.h, src/protocols/rdp/guac_ai/ai_messages.c, src/protocols/rdp/guac_ai/ai_messages.h, src/protocols/rdp/guac_ai/ai_service.c, src/protocols/rdp/guac_ai/ai_service.h, src/protocols/rdp/ptr_string.c, src/protocols/rdp/ptr_string.h, src/protocols/rdp/rdp.c, src/protocols/rdp/rdp.h, src/protocols/rdp/rdp_disp.c, src/protocols/rdp/rdp_disp.h, src/protocols/rdp/rdp_settings.c, src/protocols/rdp/rdp_settings.h, src/protocols/rdp/user.c
Yes, it is a very large change.
=> GUACAMOLE-25: Add audio input support to RDP

README
It looks like only the README had to be touched here.
=> GUACAMOLE-107 Remove references to old website and Apachify project name

src/protocols/rdp/Makefile.am, src/protocols/rdp/keymaps/fr_ch_qwertz.keymap
Rebased on behalf of @Robin-73 for #33 and in place of #54 by @jmroth, which implements the same.
=> GUACAMOLE-135: Add Swiss-French keymap for RDP.

src/common-ssh/ssh.c
GUACAMOLE-396: guacd cannot connect to ssh servers with IPv6 addresses
Root Cause:
In the ssh library of guacd, the TCP socket for connecting to ssh server is created with AF_INET. So it does not support IPv6 address.
Solution:
When guacd creates the socket for ssh in guac_common_ssh_create_session(), stop using hard coded AF_INET for socket() call, use the address family which is returned from getaddrinfo().
Test:
- Connected successfully via ssh connections with IPv4 and IPv6 hosts.
- No connection error in guacd logs.
- Simulated a connection failure with specifying a ssh server which does not exist. guacd worked well in this case.
=> GUACAMOLE-396: Fixing ssh socket for IPv6 address

src/common/cursor.c, src/common/display.c, src/protocols/vnc/user.c
More information you can see in the issue description: https://issues.apache.org/jira/browse/GUACAMOLE-424
=> GUACAMOLE-424: Fix null pointer dereference for vnc client display

src/common/surface.c
These changes dynamically scale JPEG/WebP quality based on real-time measurements of processing lag. This has the effect that slower clients will tend to be sent less data to process, and spikes in frame duration / processing tend to smooth out naturally.
=> GUACAMOLE-632: Dynamically scale JPEG/WebP quality depending on measured processing lag.

src/libguac/guacamole/protocol.h, src/libguac/guacamole/user.h, src/libguac/protocol.c, src/libguac/user-handlers.c, src/libguac/user-handlers.h, src/libguac/user-handshake.c, src/libguac/user.c, src/protocols/kubernetes/settings.c, src/protocols/rdp/rdp_settings.c, src/protocols/ssh/settings.c, src/protocols/telnet/settings.c, src/protocols/vnc/settings.c
This adds remaining pieces of the server code needed to make the timezone part of the client handshake.
=> GUACAMOLE-422: Add timezone to client handshake

src/protocols/rdp/Makefile.am, src/protocols/rdp/keymaps/hu_hu_qwertz.keymap
Please add these changes to code base to add Hunagarian keyboard support in Guacamole RDP client
=> GUACAMOLE-837: Add RDP keymap for Hungarian keyboard layout

src/protocols/rdp/Makefile.am, src/protocols/rdp/keymaps/es_latam_qwerty.keymap
I have recreated the patch with a new clean guacamole-server
Hope this solves everything now.
Best Regards,
=> GUACAMOLE-625: Included Latin American keymap

src/protocols/rdp/channels/cliprdr.c
I have fixed GUACAMOLE-947 issue registered by me.
=> GUACAMOLE-947: Fix the initialization issue of CLIPRDR_FORMAT_LIST object

src/common-ssh/sftp.c
The intent of the previous version of the SFTP directory listing code was to break the JSON transfer at blob boundaries, waiting for an ack before sending the next blob, however the ordering of the `blob_written` and directory read checks could result in a directory entry being skipped at the boundary of each blob.
The proper order would be to check the `blob_written` flag first, however the `blob_written` flag is unnecessary. It's simpler and more correct to just break out of the loop once the desired blob has been flushed.
=> GUACAMOLE-818: Break SFTP directory JSON at blob boundaries. Do not skip entries.

src/protocols/rdp/channels/rail.c
As of FreeRDP 2.0.0, handling of the RAIL handshake is no longer automatic. This was recognized and partly handled when the migration to FreeRDP 2.0.0 occurred, but we are still missing the required Handshake PDU.
Lacking the Handshake PDU, the RemoteApp session appears to start successfully but will eventually mysteriously disconnect on its own.
This change sends the Handshake PDU in response to the Handshake/HandshakeEx PDU received from the server before proceeding with the rest of the RemoteApp initialization process.
=> GUACAMOLE-978: Respond to Handshake/HandshakeEx PDU received via RAIL with client Handshake PDU.

src/common/common/defaults.h, src/libguac/Makefile.am, src/libguac/guacamole/wol-constants.h, src/libguac/guacamole/wol.h, src/libguac/wol.c, src/protocols/rdp/rdp.c, src/protocols/rdp/settings.c, src/protocols/rdp/settings.h, src/protocols/ssh/settings.c, src/protocols/ssh/settings.h, src/protocols/ssh/ssh.c, src/protocols/telnet/settings.c, src/protocols/telnet/settings.h, src/protocols/telnet/telnet.c, src/protocols/vnc/settings.c, src/protocols/vnc/settings.h, src/protocols/vnc/vnc.c
Okay, rough start, here, I'm sure, but hopefully not too bad :-).  I used a couple of examples I found online to guide me in writing my code, so hopefully it makes sense.  Let me know what needs to be fixed.
=> GUACAMOLE-513: Implement Wake-on-LAN support in libguac

src/common/clipboard.c, src/protocols/rdp/print-job.c
I have fixed the GUACAMOLE-1114 issue.
=> GUACAMOLE-1114: Fix the destruction of some thread mutexes

src/guacd/daemon.c
`guacd` cannot currently bind to IPv6 addresses (ie. the IPv6 anyaddress `::`), due to `AF_INET` being explicitly specified when creating the socket using `socket(AF_INET, ...)`.
This PR changes that in a convervative way and enables `guacd` to switch to the IPv6 address family in case no IPv4 address is returned by `getaddrinfo()`. No creating a `AF_INET6` at this point would always cause the later call to `bind()` to fail.
The added code may later be further enhanced to try to more aggressively bind to IPv6 on all supported operating systems. Unfortunately IPv6 socket behavior differs a bit between platforms and also depends on OS settings, thus the conservative approach.
For now this is mostly useful to support explicit IPv6-only deployments and has been tested to reliably bind to IPv6 …
=> GUACAMOLE-1190: Create AF_INET6 socket if no IPv4 addresses are available

src/protocols/rdp/keymaps/pt_br_qwerty.keymap
Key /? was being recognized as "right shift".
=> GUACAMOLE-1305: Fix pt-br keyboard layout

src/guacenc/ffmpeg-compat.c
This change leverages `av_packet_alloc()` and `av_packet_free()` to dynamically allocate lavc packets after the support is available, relying on static allocation only where not deprecated.
This should finally correct those repeated build failures against Ubuntu rolling and Debian testing.
=> GUACAMOLE-1330: Dynamically allocate AVPacket when possible (static allocation deprecated as of libavcodec 58.133.100).

src/guacd-docker/bin/link-freerdp-plugins.sh
The changes in https://github.com/apache/guacamole-server/pull/371 broke the installation of the FreeRDP plugins. 
Due to a difference in the way libraries are linked in the new build, there are no direct links from the FreeRDP plugins to the FreeRDP libraries, so the `where_is_freerdp` function would return an empty string, resulting in the plugins being linked into `/freerdp2`.
This change does 2 things:
1. Modify the FreeRDP installation directory search to directly search the filesystem for the expected `.so` files instead of assuming that they'll be linked against the plugins.
2. Ensure that a FreeRDP installation directory is actually found; abort the build if it isn't.
=> GUACAMOLE-1540: Search for libfreerdp2 installation directly instead of checking links.

src/protocols/rdp/Makefile.am, src/protocols/rdp/keymaps/fr_ca_qwerty.keymap
This is from kavenr.
I hope this is the only thing that needs to be updated.
I didnt find those files in my container, so I could change them to test. Maybe I didnt check at the right places.
I can confirm the keymap is correct.
=> GUACAMOLE-1312: Adds Canadian French keymaps

src/protocols/rdp/bitmap.c, src/protocols/rdp/channels/common-svc.h, src/protocols/rdp/channels/disp.h, src/protocols/rdp/channels/rdpei.h, src/protocols/rdp/channels/rdpgfx.h, src/protocols/rdp/gdi.c, src/protocols/rdp/glyph.h, src/protocols/rdp/keyboard.c, src/protocols/rdp/plugins/guacai/guacai-messages.c, src/protocols/rdp/settings.c
I've just fixed some typo mistakes.
=> GUACAMOLE-1636: Fixed some typo mistakes.

src/guacenc/ffmpeg-compat.c, src/guacenc/ffmpeg-compat.h, src/guacenc/video.c
This change is simply a direct copy of the changes proposed via #379, amended to include the JIRA issue in the commit message.
This closes #379.
=> GUACAMOLE-1714: Update guacenc for const parameters/values introduced in FFmpeg 5.0.

src/protocols/rdp/channels/audio-input/audio-buffer.c
The function `guac_rdp_audio_buffer_ack()` is the only location in guacamole-server where a `guac_user` instance is accessed outside the context of a user-specific callback, a no-no in the libguac API. This change migrates that function such that it _is_ a callback, invoked by `guac_client_for_user()` (the function provided by libguac for exactly this purpose).
=> GUACAMOLE-1784: Migrate usage of guac_rdp_audio_buffer_ack() to guac_client_for_user().

src/protocols/rdp/settings.c
This change reapplies the same commits from #392 against `staging/1.5.2`.
=> GUACAMOLE-1674: Warn about NLA mode if FIPS mode is enabled, or disable if possible.

src/protocols/telnet/settings.c, src/protocols/telnet/settings.h, src/protocols/telnet/telnet.c
Add support for specifying the connection timeout for Telnet connections.
=> GUACAMOLE-600: Add support for setting the Telnet connection timeout.

Dockerfile
Fixed the issue to show the garbled Japanese text in SSH.
=> GUACAMOLE-1726: Fix the issue to show the garbled Japanese text in SSH.

src/libguac/error.c, src/libguac/guacamole/error-types.h
Fixed the spell errors in the identifiers of some constants.
=> GUACAMOLE-1912: Fix the spell errors in the identifiers of some constants.

src/libguac/guacamole/recording.h, src/libguac/recording.c, src/protocols/kubernetes/kubernetes.c, src/protocols/kubernetes/settings.c, src/protocols/kubernetes/settings.h, src/protocols/rdp/rdp.c, src/protocols/rdp/settings.c, src/protocols/rdp/settings.h, src/protocols/ssh/settings.c, src/protocols/ssh/settings.h, src/protocols/ssh/ssh.c, src/protocols/telnet/settings.c, src/protocols/telnet/settings.h, src/protocols/telnet/telnet.c, src/protocols/vnc/settings.c, src/protocols/vnc/settings.h, src/protocols/vnc/vnc.c
See also https://github.com/apache/guacamole-client/pull/961
=> GUACAMOLE-1931: Allow writing to existing recording files.

src/libguac/display-flush.c
The actual addition of operations to the `ops` FIFO has to happen atomically, or else an earlier frame's operations may end up in the FIFO _after_ a later frame's operations.
This is the cause of the odd smearing artifacts during scrolling when the system is under heavy load.
=> GUACAMOLE-377: Correct race condition in guac_display flush planning.

src/libguac/wol.c
This change refactors the internals of the Wake-on-LAN address conversion such that it properly uses the `struct sockaddr_in` or `struct sockaddr_in6` structures depending on whether IPv4 or IPv6 is being used, leveraging the magic of `struct sockaddr_storage` (a structure that is guaranteed to have proper size and alignment for any supported socket type).
=> GUACAMOLE-2070: Correct usage of struct sockaddr_in / sockaddr_in6.
